In [1]:
#test_target_b_parquet

In [1]:
import numpy as np
import pandas as pd

,Unnamed: 0,client_id,target_1,target_2,target_3,target_4
0,0,2b7ff0c1c99cefe259ed83c5dfa0a403f2cbc88032b671...,0.001422,0.000176,0.088572,0.003422
1,1,0433d23e224b7a520656da6181efadb8d556bb293158c9...,0.014299,0.000435,0.010419,0.003007
2,2,f2ce8b292e5f9f778f3e20db7608ac76dc8812113a2631...,0.017853,0.007523,0.010701,0.021349
3,3,4f807e8b163c653bcaeff9f925983568f4c3e6b1a1f231...,0.010975,0.004356,0.025208,0.026687
4,4,64369f6f8ae1b719332ee1bfb2b454e642b2053d2c9b8a...,0.010453,0.000531,0.010711,0.001758
...,...,...,...,...,...,...
140483,140483,d49a66825bb16ceb5b6a01126e1f2391b085dba8da44ee...,0.010042,0.002497,0.017207,0.007788
140484,140484,f772af6720c0b591d49b97946c5e420c1c077affc0f7c7...,0.008701,0.000476,0.004393,0.016346
140485,140485,06b282335bc4853f888e1ab50a6ba23a8e420d42313959...,0.009764,0.002151,0.010213,0.002264
140486,140486,90d423a25d7cdaf674f7d78bc37d88830443ff17717e02...,0.016902,0.000972,0.014184,0.037340
140487,140487,f63e55b226d3732b8b4927be8a2cdc7fb88ff2bb0561e2...,0.007528,0.000687,0.004786,0.004292

In [723]:
import pandas as pd
import os

# Укажите путь к папке с файлами Parquet
folder_path = 'train_target_parquet'

# Получите список всех файлов Parquet в папке
parquet_files = [f for f in os.listdir(folder_path) if f.endswith('.parquet')]

# Создайте пустой DataFrame для объединения данных
combined_df = pd.DataFrame()

# Прочитайте и объедините каждый файл Parquet
for file in parquet_files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_parquet(file_path)
    combined_df = pd.concat([combined_df, df], ignore_index=True)



combined_df

,mon,target_1,target_2,target_3,target_4,client_id
0,2022-06-30,0,0,0,0,1d4ebf30ab5b981c60a6596e8daa4bdc0646163e50e486...
1,2022-07-31,0,0,0,0,1d4ebf30ab5b981c60a6596e8daa4bdc0646163e50e486...
2,2022-08-31,0,0,0,0,1d4ebf30ab5b981c60a6596e8daa4bdc0646163e50e486...
3,2022-09-30,0,0,0,0,1d4ebf30ab5b981c60a6596e8daa4bdc0646163e50e486...
4,2022-10-31,0,0,0,0,1d4ebf30ab5b981c60a6596e8daa4bdc0646163e50e486...
...,...,...,...,...,...,...
10246699,2022-05-31,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...
10246700,2022-06-30,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...
10246701,2022-07-31,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...
10246702,2022-08-31,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...
10246703,2022-09-30,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...

In [724]:
df_test = combined_df

In [725]:
df_test['period'] = pd.to_datetime(df_test['mon'])

In [726]:
df_test = df_test.drop(columns = ['mon'])

In [727]:
df_test

,target_1,target_2,target_3,target_4,client_id,period
0,0,0,0,0,1d4ebf30ab5b981c60a6596e8daa4bdc0646163e50e486...,2022-06-30
1,0,0,0,0,1d4ebf30ab5b981c60a6596e8daa4bdc0646163e50e486...,2022-07-31
2,0,0,0,0,1d4ebf30ab5b981c60a6596e8daa4bdc0646163e50e486...,2022-08-31
3,0,0,0,0,1d4ebf30ab5b981c60a6596e8daa4bdc0646163e50e486...,2022-09-30
4,0,0,0,0,1d4ebf30ab5b981c60a6596e8daa4bdc0646163e50e486...,2022-10-31
...,...,...,...,...,...,...
10246699,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...,2022-05-31
10246700,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...,2022-06-30
10246701,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...,2022-07-31
10246702,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...,2022-08-31
10246703,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...,2022-09-30

In [728]:
# Получаем уникальные client_id
unique_client_ids = df_test['client_id'].unique()

# Определяем размер выборки для 1/25
sample_size = len(unique_client_ids) // 30

# Перемешиваем уникальные client_id
#np.random.shuffle(unique_client_ids)

# Создаем список для хранения DataFrame для каждой части
dfs = []
s = 0
# Разделяем на 25 частей
for i in range(25):
    if i == 24:  # Для последней части включаем все оставшиеся элементы
        part_client_ids = unique_client_ids[i*sample_size:]
    else:
        part_client_ids = unique_client_ids[i*sample_size:(i+1)*sample_size]
    part_df = df_test[df_test['client_id'].isin(part_client_ids)]
    dfs.append(part_df)
    s+=len(part_df)
    print(f"Размер части {i+1}: {len(part_df)} записей")

# Возвращаем список DataFrame
print(len(dfs),s)

Размер части 1: 341556 записей
Размер части 2: 341556 записей
Размер части 3: 341556 записей
Размер части 4: 341556 записей
Размер части 5: 341556 записей
Размер части 6: 341556 записей
Размер части 7: 341556 записей
Размер части 8: 341556 записей
Размер части 9: 341556 записей
Размер части 10: 341556 записей
Размер части 11: 341556 записей
Размер части 12: 341556 записей
Размер части 13: 341556 записей
Размер части 14: 341556 записей
Размер части 15: 341556 записей
Размер части 16: 341556 записей
Размер части 17: 341556 записей
Размер части 18: 341556 записей
Размер части 19: 341556 записей
Размер части 20: 341556 записей
Размер части 21: 341556 записей
Размер части 22: 341556 записей
Размер части 23: 341556 записей
Размер части 24: 341556 записей
Размер части 25: 2049360 записей
25 10246704

In [729]:
df_test['client_id'].nunique()

853892

In [730]:
df_test

,target_1,target_2,target_3,target_4,client_id,period
0,0,0,0,0,1d4ebf30ab5b981c60a6596e8daa4bdc0646163e50e486...,2022-06-30
1,0,0,0,0,1d4ebf30ab5b981c60a6596e8daa4bdc0646163e50e486...,2022-07-31
2,0,0,0,0,1d4ebf30ab5b981c60a6596e8daa4bdc0646163e50e486...,2022-08-31
3,0,0,0,0,1d4ebf30ab5b981c60a6596e8daa4bdc0646163e50e486...,2022-09-30
4,0,0,0,0,1d4ebf30ab5b981c60a6596e8daa4bdc0646163e50e486...,2022-10-31
...,...,...,...,...,...,...
10246699,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...,2022-05-31
10246700,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...,2022-06-30
10246701,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...,2022-07-31
10246702,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...,2022-08-31
10246703,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...,2022-09-30

In [731]:
dfs[6]

,target_1,target_2,target_3,target_4,client_id,period
2049320,0,0,0,0,4e406de266cc51aee62f3cc910bbdd0f232ebab1324a5b...,2022-02-28
2049321,0,0,0,0,4e406de266cc51aee62f3cc910bbdd0f232ebab1324a5b...,2022-03-31
2049322,0,0,0,0,4e406de266cc51aee62f3cc910bbdd0f232ebab1324a5b...,2022-04-30
2049323,0,0,0,0,4e406de266cc51aee62f3cc910bbdd0f232ebab1324a5b...,2022-05-31
2049324,0,0,0,0,4e406de266cc51aee62f3cc910bbdd0f232ebab1324a5b...,2022-06-30
...,...,...,...,...,...,...
10246699,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...,2022-05-31
10246700,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...,2022-06-30
10246701,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...,2022-07-31
10246702,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...,2022-08-31
10246703,0,0,0,0,fff788a41d760a38d02f13cb0f3e872144e071500f2dbe...,2022-09-30

In [732]:
# Получаем уникальные client_id
#unique_client_ids = df_test['client_id'].unique()
# Выбираем случайные 10% уникальных client_id
#sample_size = int(len(unique_client_ids) * 0.5)
#sampled_client_ids = np.random.choice(unique_client_ids, sample_size, replace=False)
# Фильтруем датасет по выбранным client_id
filtered_df = dfs[24]
unique_client_ids = filtered_df['client_id'].unique()

In [736]:
filtered_df

,target_1,target_2,target_3,target_4,client_id,period
8197328,0,0,0,0,842fc3467201d654cda5e5e77b02b4a5ff4aadc029d24e...,2
8197329,0,0,0,0,842fc3467201d654cda5e5e77b02b4a5ff4aadc029d24e...,3
8197330,0,0,0,0,842fc3467201d654cda5e5e77b02b4a5ff4aadc029d24e...,4
8197331,0,0,0,0,842fc3467201d654cda5e5e77b02b4a5ff4aadc029d24e...,5
8197332,0,0,0,0,842fc3467201d654cda5e5e77b02b4a5ff4aadc029d24e...,6
...,...,...,...,...,...,...
10246691,0,0,0,0,ffc0a010061b30747ae785141ba9cba2f149f331a48f7f...,9
10246692,0,0,0,0,ffc0a010061b30747ae785141ba9cba2f149f331a48f7f...,10
10246693,0,0,0,0,ffc0a010061b30747ae785141ba9cba2f149f331a48f7f...,11
10246694,0,0,0,0,ffc0a010061b30747ae785141ba9cba2f149f331a48f7f...,12
10246695,0,0,0,0,ffc0a010061b30747ae785141ba9cba2f149f331a48f7f...,1

In [733]:
len(unique_client_ids)

170780

In [737]:


filtered_df = filtered_df[filtered_df['period'] == 1]
filtered_df

,target_1,target_2,target_3,target_4,client_id,period
8197339,0,0,0,0,842fc3467201d654cda5e5e77b02b4a5ff4aadc029d24e...,1
8197351,0,0,0,0,8438dae96873c7cf887006ac213a5360c31e0bcf1dc520...,1
8197363,0,0,0,0,843adde3157173a548765bb8f0f57ad19640ae7ed46919...,1
8197375,0,0,0,0,844389d046c4181ef3e5bfec83d01da83e339c9bbc23d5...,1
8197387,0,0,0,0,8472a5d44dabee5d6d7116bd91c502b8b1053d8a13b94d...,1
...,...,...,...,...,...,...
10246647,0,0,0,0,ffa66de5b0f8d3592c578af89f8eca7933f1552199cdd6...,1
10246659,0,0,0,0,ffade23e54114463d2271842ab88b38c0225cbe934f365...,1
10246671,0,0,0,0,ffbba08772b67a2a7b057a3f616f90b0601c34d5032757...,1
10246683,0,0,0,0,ffc09c3decd0f53763e4737accf686bade81f1fc86da94...,1
10246695,0,0,0,0,ffc0a010061b30747ae785141ba9cba2f149f331a48f7f...,1

In [615]:
# Получим данные за 11-й месяц
df_11_month = filtered_df[filtered_df['period'] == 11].copy()

# Получим данные за последний доступный месяц для каждого клиента
df_last_month = filtered_df.loc[filtered_df.groupby('client_id')['period'].idxmax()].copy()

# Получим сумму таргетов за все месяцы, кроме 11-го
df_sums = filtered_df[filtered_df['period'] != 11].groupby('client_id').agg({
    'target_1': 'sum',
    'target_2': 'sum',
    'target_3': 'sum'
}).reset_index()

# Переименуем столбцы
df_sums.rename(columns={
    'target_1': 'target_1_new',
    'target_2': 'target_2_new',
    'target_3': 'target_3_new'
}, inplace=True)

# Объединим df_sums с df_11_month, затем добавим недостающие значения из df_last_month
result = pd.merge(df_sums, df_11_month[['client_id', 'target_1', 'target_2', 'target_3', 'target_4']], on='client_id', how='left')

# Найдем клиентов, у которых нет данных за 11-й месяц
missing_clients = result[result[['target_1', 'target_2', 'target_3', 'target_4']].isnull().any(axis=1)]['client_id']

# Добавим недостающие данные из df_last_month
for client_id in missing_clients:
    last_row = df_last_month[df_last_month['client_id'] == client_id]
    result.loc[result['client_id'] == client_id, ['target_1', 'target_2', 'target_3', 'target_4']] = last_row[['target_1', 'target_2', 'target_3', 'target_4']].values

# Убедимся, что каждая строка уникальна для каждого клиента
result.drop_duplicates(subset='client_id', keep='first', inplace=True)

In [616]:
result['target_4'].value_counts()

target_4
0.0    27917
1.0      203
Name: count, dtype: int64

In [617]:
filtered_df = result

In [618]:
unique_client_ids = filtered_df['client_id'].unique()
len(unique_client_ids)

28120

In [619]:
filtered_df.to_parquet('main_last.parquet')

In [18]:
import pandas as pd
import os

# Укажите путь к папке с файлами Parquet
folder_path = 'trx_test_parquet'

# Получите список всех файлов Parquet в папке
parquet_files = [f for f in os.listdir(folder_path) if f.endswith('.parquet')]

# Создайте пустой DataFrame для объединения данных
combined_df = pd.DataFrame()

# Прочитайте и объедините каждый файл Parquet
for file in parquet_files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_parquet(file_path)
    combined_df = pd.concat([combined_df, df], ignore_index=True)

In [20]:
trx = combined_df
trx

,event_time,amount,client_id,event_type,event_subtype,currency,src_type11,src_type12,dst_type11,dst_type12,src_type21,src_type22,src_type31,src_type32
0,2022-09-01 22:15:48.451581,3.145942e+05,011175314a5d1c2d8349d6aef370939f3350cebca3bc26...,44,14,11.0,19.0,344.0,364.0,22652.0,40473.0,51.0,1738.0,36.0
1,2022-10-17 14:47:41.538582,5.523387e+03,011175314a5d1c2d8349d6aef370939f3350cebca3bc26...,44,14,11.0,19.0,344.0,364.0,22652.0,40473.0,51.0,1738.0,36.0
2,2022-05-15 17:08:07.266505,7.061869e+05,011175314a5d1c2d8349d6aef370939f3350cebca3bc26...,44,14,11.0,19.0,344.0,364.0,22652.0,40473.0,51.0,1738.0,36.0
3,2022-09-08 17:58:28.273298,9.013208e+05,011175314a5d1c2d8349d6aef370939f3350cebca3bc26...,44,14,11.0,72.0,682.0,364.0,22652.0,40473.0,51.0,1738.0,36.0
4,2022-09-10 20:39:37.915688,3.531739e+04,011175314a5d1c2d8349d6aef370939f3350cebca3bc26...,25,47,11.0,19.0,344.0,1166.0,30836.0,40473.0,51.0,1738.0,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47608658,2022-07-26 05:49:44.554133,1.169040e+06,fba7d41d3a60930e88edc1822a086dab1c4e93e278879b...,54,55,11.0,19.0,344.0,364.0,22652.0,25721.0,48.0,2198.0,81.0
47608659,2022-02-06 10:54:17.449562,2.462178e+03,fba7d41d3a60930e88edc1822a086dab1c4e93e278879b...,54,55,11.0,19.0,344.0,364.0,22652.0,25721.0,48.0,2198.0,81.0
47608660,2022-01-02 01:01:00.008994,5.188455e+02,fba7d41d3a60930e88edc1822a086dab1c4e93e278879b...,54,55,11.0,19.0,344.0,364.0,22652.0,25721.0,48.0,2198.0,81.0
47608661,2022-10-15 11:31:30.905121,5.816505e+03,fba7d41d3a60930e88edc1822a086dab1c4e93e278879b...,54,55,11.0,19.0,344.0,364.0,22652.0,25721.0,48.0,2198.0,81.0
47608662,2022-04-04 14:36:44.175025,1.897476e+02,fba7d41d3a60930e88edc1822a086dab1c4e93e278879b...,54,55,11.0,19.0,344.0,364.0,22652.0,25721.0,48.0,2198.0,81.0

array(['000903d094d14adcf16741d621487b8dce544d82532b8c186f988fc632878bff',
       '0024af3860e92f4be26f284f8d22c90b17b5d206589fbd43bcb5dc39df0c8d41',
       '002d2068c38fd069e2b4e4b40cc58ea16b8edaa41515f00ba30ab384f4f87f13',
       ...,
       'ffa507dac4032e7fb080f6e6cd7149fcfe475931b2ae7b565712b8d781b20dfa',
       'ffdea0519a8535db1eb55d6ab8dce5a62fd67d27e8e58237130e6eac91bb7d8c',
       'ffef3291b792dd19debe8f3674e2df3ec6b22febac969d055ba9c1527dd7bfd1'],
      dtype=object)

In [620]:
combined_df = trx[trx['client_id'].isin(unique_client_ids)]
#combined_df = combined_df[combined_df['event_time'].dt.month == 2]

In [600]:
trx

,event_time,amount,client_id,event_type,event_subtype,currency,src_type11,src_type12,dst_type11,dst_type12,src_type21,src_type22,src_type31,src_type32
0,2022-09-01 22:15:48.451581,3.145942e+05,011175314a5d1c2d8349d6aef370939f3350cebca3bc26...,44,14,11.0,19.0,344.0,364.0,22652.0,40473.0,51.0,1738.0,36.0
1,2022-10-17 14:47:41.538582,5.523387e+03,011175314a5d1c2d8349d6aef370939f3350cebca3bc26...,44,14,11.0,19.0,344.0,364.0,22652.0,40473.0,51.0,1738.0,36.0
2,2022-05-15 17:08:07.266505,7.061869e+05,011175314a5d1c2d8349d6aef370939f3350cebca3bc26...,44,14,11.0,19.0,344.0,364.0,22652.0,40473.0,51.0,1738.0,36.0
3,2022-09-08 17:58:28.273298,9.013208e+05,011175314a5d1c2d8349d6aef370939f3350cebca3bc26...,44,14,11.0,72.0,682.0,364.0,22652.0,40473.0,51.0,1738.0,36.0
4,2022-09-10 20:39:37.915688,3.531739e+04,011175314a5d1c2d8349d6aef370939f3350cebca3bc26...,25,47,11.0,19.0,344.0,1166.0,30836.0,40473.0,51.0,1738.0,36.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47608658,2022-07-26 05:49:44.554133,1.169040e+06,fba7d41d3a60930e88edc1822a086dab1c4e93e278879b...,54,55,11.0,19.0,344.0,364.0,22652.0,25721.0,48.0,2198.0,81.0
47608659,2022-02-06 10:54:17.449562,2.462178e+03,fba7d41d3a60930e88edc1822a086dab1c4e93e278879b...,54,55,11.0,19.0,344.0,364.0,22652.0,25721.0,48.0,2198.0,81.0
47608660,2022-01-02 01:01:00.008994,5.188455e+02,fba7d41d3a60930e88edc1822a086dab1c4e93e278879b...,54,55,11.0,19.0,344.0,364.0,22652.0,25721.0,48.0,2198.0,81.0
47608661,2022-10-15 11:31:30.905121,5.816505e+03,fba7d41d3a60930e88edc1822a086dab1c4e93e278879b...,54,55,11.0,19.0,344.0,364.0,22652.0,25721.0,48.0,2198.0,81.0
47608662,2022-04-04 14:36:44.175025,1.897476e+02,fba7d41d3a60930e88edc1822a086dab1c4e93e278879b...,54,55,11.0,19.0,344.0,364.0,22652.0,25721.0,48.0,2198.0,81.0

In [621]:
combined_df

,event_time,amount,client_id,event_type,event_subtype,currency,src_type11,src_type12,dst_type11,dst_type12,src_type21,src_type22,src_type31,src_type32
32796,2022-07-02 00:09:53.648397,1.026919e+02,fb1f1ba6634a758d30dfa31a81c99d7d48cc03e7190622...,45,2,11.0,70.0,1091.0,1166.0,30836.0,21728.0,47.0,2493.0,81.0
32797,2022-02-16 09:00:04.677911,2.394046e+06,fb1f1ba6634a758d30dfa31a81c99d7d48cc03e7190622...,48,43,11.0,19.0,344.0,364.0,22652.0,21728.0,47.0,2493.0,81.0
32798,2022-08-29 23:36:03.394896,5.338342e+02,fb1f1ba6634a758d30dfa31a81c99d7d48cc03e7190622...,45,2,11.0,70.0,1091.0,1166.0,30836.0,21728.0,47.0,2493.0,81.0
32799,2022-01-03 07:24:10.618468,8.247124e+05,fb1f1ba6634a758d30dfa31a81c99d7d48cc03e7190622...,54,55,11.0,19.0,344.0,364.0,22652.0,21728.0,47.0,2493.0,81.0
32800,2022-03-19 07:20:02.444292,7.342644e+06,fb1f1ba6634a758d30dfa31a81c99d7d48cc03e7190622...,54,55,11.0,19.0,344.0,364.0,22652.0,21728.0,47.0,2493.0,81.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47592365,2022-07-02 05:20:56.150296,1.174848e+02,926e640fa8b3f47b63c4868214a0d08bbe1ff690720c93...,37,18,11.0,19.0,344.0,433.0,10049.0,17741.0,70.0,591.0,88.0
47592366,2022-02-19 02:30:12.167774,8.704519e+01,926e640fa8b3f47b63c4868214a0d08bbe1ff690720c93...,37,18,11.0,19.0,344.0,433.0,10049.0,17741.0,70.0,591.0,88.0
47592367,2022-02-23 07:53:57.329831,1.902847e+02,926e640fa8b3f47b63c4868214a0d08bbe1ff690720c93...,37,18,11.0,19.0,344.0,433.0,10049.0,17741.0,70.0,591.0,88.0
47592368,2022-01-25 05:29:50.831856,1.227525e+03,926e640fa8b3f47b63c4868214a0d08bbe1ff690720c93...,37,18,11.0,19.0,344.0,433.0,10049.0,17741.0,70.0,591.0,88.0
47592369,2022-01-11 16:20:50.303329,1.980028e+03,926e640fa8b3f47b63c4868214a0d08bbe1ff690720c93...,37,18,11.0,19.0,344.0,852.0,25683.0,17741.0,70.0,591.0,88.0

In [622]:
import pandas as pd

def transform_group_trx(group):
    client_id = group['client_id'].iloc[0]
    client_data = {'client_id': client_id}
    for idx, row in enumerate(group.itertuples(index=False), 1):
        if idx > 5:  # Ограничиваем количество столбцов
            break
        suffix = f'_{idx}'
        client_data[f'amount{suffix}'] = row.amount
        client_data[f'event_type{suffix}'] = row.event_type
        client_data[f'currency{suffix}'] = row.currency
        client_data[f'src_type11{suffix}'] = row.src_type11
        client_data[f'src_type12{suffix}'] = row.src_type12
        client_data[f'dst_type11{suffix}'] = row.dst_type11
        client_data[f'dst_type12{suffix}'] = row.dst_type12
        client_data[f'src_type21{suffix}'] = row.src_type21
        client_data[f'src_type22{suffix}'] = row.src_type22
        client_data[f'src_type31{suffix}'] = row.src_type31
        client_data[f'src_type32{suffix}'] = row.src_type32
    return pd.DataFrame([client_data])

def trans_trx(df):
    # Замена NaN значений
    df = df.fillna({
        'amount': 0,
        'event_type': 0,
        'event_subtype': 0,
        'currency': 0,
        'src_type11': 0,
        'src_type12': 0,
        'dst_type11': 0,
        'dst_type12': 0,
        'src_type21': 0,
        'src_type22': 0,
        'src_type31': 0,
        'src_type32': 0
    })
    df = df.astype({
        'amount': 'float32',
        'client_id': 'string',
        'event_type': 'int32',
        'event_subtype': 'int32',
        'currency': 'int32',
        'src_type11': 'int32',
        'src_type12': 'int32',
        'dst_type11': 'int32',
        'dst_type12': 'int32',
        'src_type21': 'int32',
        'src_type22': 'int32',
        'src_type31': 'int32',
        'src_type32': 'int32'
    })
    
    # Группировка и применение функции
    transformed = df.groupby('client_id').apply(transform_group_trx).reset_index(drop=True)
    
    return transformed


# Пример использования
# Предполагается, что df_trx уже загружен как Pandas DataFrame
res_trx = trans_trx(combined_df)

In [623]:
res_trx['client_id'].nunique()

19136

In [624]:
res_trx = res_trx.fillna(0)
res_trx

,client_id,amount_1,event_type_1,currency_1,src_type11_1,src_type12_1,dst_type11_1,dst_type12_1,src_type21_1,src_type22_1,...,event_type_5,currency_5,src_type11_5,src_type12_5,dst_type11_5,dst_type12_5,src_type21_5,src_type22_5,src_type31_5,src_type32_5
0,00066ddb37c6a9cc8aef6404b3f485322501d6b2baefb4...,1.207451e+06,44,11,19,344,364,22652,3824,48,...,44.0,11.0,19.0,344.0,364.0,22652.0,3824.0,48.0,942.0,4.0
1,000757cdc288fb1095fa51b8f98166bc2d29bc5f6ea708...,4.103641e+03,37,11,19,902,433,10049,22294,72,...,37.0,11.0,19.0,902.0,433.0,10049.0,22294.0,72.0,1054.0,16.0
2,000d00eb3817aa52cc39c069f18cf7bf01444720a0c981...,2.768226e+03,38,11,19,344,813,20641,37565,70,...,38.0,11.0,19.0,344.0,813.0,20641.0,37565.0,70.0,522.0,55.0
3,0011e86bf25a8ff48d4092b7d97450b8ab4eb807f69320...,1.149264e+06,51,11,19,344,869,17340,11274,20,...,54.0,11.0,19.0,344.0,869.0,31488.0,11274.0,20.0,1037.0,2.0
4,00136b2bb7c74fa8fb5362311096d4d69d652064d1cca8...,1.480450e+02,54,11,19,344,364,22652,30151,70,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19131,fff4b0121e176fef8fd29b65d92a554ac5118d84deca79...,8.670344e+03,37,11,19,344,433,10049,42260,63,...,37.0,11.0,19.0,344.0,433.0,10049.0,42260.0,63.0,1825.0,26.0
19132,fff89e27c8947ce6beb0d915306b14db75ab50d94b9be4...,1.214823e+05,54,11,19,902,364,22652,15518,24,...,54.0,11.0,19.0,902.0,364.0,22652.0,15518.0,24.0,1835.0,26.0
19133,fffbcae1f0b7a651ad9ca6acbe35fd193aeafa2f9bc227...,1.580148e+03,37,11,19,344,433,10049,47714,48,...,37.0,11.0,19.0,344.0,433.0,10049.0,47714.0,48.0,2239.0,81.0
19134,fffd127b61250edd960e8751b25f372d164e5cbb89761a...,8.585744e-02,16,11,19,344,813,18723,26311,41,...,16.0,11.0,19.0,344.0,813.0,18723.0,26311.0,41.0,2468.0,4.0
19135,fffd1b037b3e6449de57d74e635021a3803e642a82dd2f...,6.012142e+03,37,11,19,344,433,10049,15373,70,...,37.0,11.0,19.0,344.0,433.0,10049.0,15373.0,70.0,1897.0,65.0

In [625]:
res_trx.to_parquet('trx_last.parquet')

In [29]:
import pandas as pd
import os

# Укажите путь к папке с файлами Parquet
folder_path = 'geo_test_parquet'

# Получите список всех файлов Parquet в папке
parquet_files = [f for f in os.listdir(folder_path) if f.endswith('.parquet')]

# Создайте пустой DataFrame для объединения данных
combined_df = pd.DataFrame()

# Прочитайте и объедините каждый файл Parquet
for file in parquet_files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_parquet(file_path)
    combined_df = pd.concat([combined_df, df], ignore_index=True)

In [30]:
geo = combined_df

In [31]:
df_geo = combined_df

In [626]:
df_geo = geo[geo['client_id'].isin(unique_client_ids)]
#df_geo = df_geo[df_geo['event_time'].dt.month ==2]
df_geo

,client_id,event_time,geohash_4,geohash_5,geohash_6
101130,0ceaad41e8642c1608a77d0066c91ad8abef27230771e8...,2022-06-01 11:07:34.218891,21584,363762,749862
101131,0ceaad41e8642c1608a77d0066c91ad8abef27230771e8...,2022-08-25 11:57:09.748511,27542,153715,1410526
101132,0ceaad41e8642c1608a77d0066c91ad8abef27230771e8...,2022-07-04 08:10:22.613798,21584,363762,749862
101133,0ceaad41e8642c1608a77d0066c91ad8abef27230771e8...,2022-08-06 15:15:30.514246,27542,153715,1410526
101134,0ceaad41e8642c1608a77d0066c91ad8abef27230771e8...,2022-08-17 12:23:53.801091,21584,363762,749862
...,...,...,...,...,...
138988139,f2649552cfbe2eff9324669e2b52d55b85f08ddf593d4b...,2022-04-18 09:07:34.164254,29564,206625,2522656
138988140,f2649552cfbe2eff9324669e2b52d55b85f08ddf593d4b...,2022-02-07 08:26:53.924625,35066,395161,2321920
138988141,f2649552cfbe2eff9324669e2b52d55b85f08ddf593d4b...,2022-02-20 06:16:01.681534,35066,395161,2321920
138988142,f2649552cfbe2eff9324669e2b52d55b85f08ddf593d4b...,2022-02-16 07:44:52.235334,35066,395161,2321920
138988143,f2649552cfbe2eff9324669e2b52d55b85f08ddf593d4b...,2022-03-09 18:28:24.501012,5147,343392,2739972

In [627]:
import pandas as pd

def transform_group_trx(group):
    client_id = group['client_id'].iloc[0]
    client_data = {'client_id': client_id}
    for idx, row in enumerate(group.itertuples(index=False), 1):
        if idx > 5:  # Ограничиваем количество столбцов
            break
        suffix = f'_{idx}'
        client_data[f'geohash_4{suffix}'] = row.geohash_4
        client_data[f'geohash_5{suffix}'] = row.geohash_5
        client_data[f'geohash_6{suffix}'] = row.geohash_6

    return pd.DataFrame([client_data])

def trans_trx(df):
    # Замена NaN значений
    df = df.fillna({
        'geohash_4': 0,
        'geohash_5': 0,
        'geohash_6': 0,

    })
    df = df.astype({
        'geohash_4': 'float32',
        'geohash_5': 'float32',
        'geohash_6': 'float32',

    })
    
    # Группировка и применение функции
    transformed = df.groupby('client_id').apply(transform_group_trx).reset_index(drop=True)
    
    return transformed


# Пример использования
# Предполагается, что df_trx уже загружен как Pandas DataFrame
res_geo = trans_trx(df_geo)

In [628]:
df_geo['client_id'].nunique()

14863

In [629]:
res_geo

,client_id,geohash_4_1,geohash_5_1,geohash_6_1,geohash_4_2,geohash_5_2,geohash_6_2,geohash_4_3,geohash_5_3,geohash_6_3,geohash_4_4,geohash_5_4,geohash_6_4,geohash_4_5,geohash_5_5,geohash_6_5
0,00066ddb37c6a9cc8aef6404b3f485322501d6b2baefb4...,1201.0,207870.0,2621280.0,17422.0,253443.0,2093422.0,881.0,355868.0,2734460.0,17422.0,253443.0,2093422.0,881.0,355868.0,2734460.0
1,000d00eb3817aa52cc39c069f18cf7bf01444720a0c981...,17663.0,78557.0,1481635.0,48838.0,48705.0,1161521.0,22879.0,69963.0,139171.0,8773.0,339002.0,127224.0,27225.0,346893.0,777267.0
2,0011e86bf25a8ff48d4092b7d97450b8ab4eb807f69320...,5147.0,165006.0,1403192.0,21278.0,140231.0,217372.0,5147.0,165006.0,933687.0,21278.0,140231.0,217372.0,21278.0,296199.0,2261703.0
3,00136b2bb7c74fa8fb5362311096d4d69d652064d1cca8...,1480.0,120013.0,1817713.0,22879.0,139461.0,1494199.0,22879.0,134932.0,555522.0,22879.0,139461.0,1494199.0,22879.0,134932.0,555522.0
4,001add687efe40428764e5e1e85ea13f94f1ac431b67c7...,2015.0,100898.0,1677582.0,18415.0,335548.0,415329.0,2015.0,100898.0,1677582.0,18415.0,252759.0,931871.0,2015.0,100898.0,1677582.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14858,ffef0bb8c8b21ffa989e460c774c1db7e5b1b47abd3ed7...,10488.0,23893.0,968080.0,9867.0,52676.0,723052.0,10488.0,296103.0,2283348.0,9867.0,52676.0,723052.0,23765.0,54545.0,1039963.0
14859,ffef318c5e1f4114ddf0225c0ae3f233b2ae2ff3ee4403...,49531.0,53115.0,1303569.0,20350.0,396234.0,211788.0,49531.0,53115.0,1303569.0,16169.0,115850.0,2030393.0,49531.0,53115.0,1303569.0
14860,fff0032cb902d90e0afd207446a2ff207b1b46e89b0482...,46299.0,166446.0,2724958.0,7427.0,18501.0,65699.0,7427.0,18501.0,1498464.0,7427.0,18501.0,65699.0,7427.0,18501.0,1498464.0
14861,fff4107e48a94c6a1fc884b78a93d8d194237840d7e656...,46849.0,363086.0,664882.0,30874.0,122063.0,1388441.0,46849.0,363086.0,664882.0,46849.0,266947.0,2600670.0,46849.0,363086.0,664882.0
14862,fffbcae1f0b7a651ad9ca6acbe35fd193aeafa2f9bc227...,881.0,389010.0,191878.0,881.0,389010.0,191878.0,881.0,389010.0,191878.0,881.0,389010.0,191878.0,881.0,389010.0,191878.0

In [630]:
res_geo = res_geo.fillna(0)
res_geo

,client_id,geohash_4_1,geohash_5_1,geohash_6_1,geohash_4_2,geohash_5_2,geohash_6_2,geohash_4_3,geohash_5_3,geohash_6_3,geohash_4_4,geohash_5_4,geohash_6_4,geohash_4_5,geohash_5_5,geohash_6_5
0,00066ddb37c6a9cc8aef6404b3f485322501d6b2baefb4...,1201.0,207870.0,2621280.0,17422.0,253443.0,2093422.0,881.0,355868.0,2734460.0,17422.0,253443.0,2093422.0,881.0,355868.0,2734460.0
1,000d00eb3817aa52cc39c069f18cf7bf01444720a0c981...,17663.0,78557.0,1481635.0,48838.0,48705.0,1161521.0,22879.0,69963.0,139171.0,8773.0,339002.0,127224.0,27225.0,346893.0,777267.0
2,0011e86bf25a8ff48d4092b7d97450b8ab4eb807f69320...,5147.0,165006.0,1403192.0,21278.0,140231.0,217372.0,5147.0,165006.0,933687.0,21278.0,140231.0,217372.0,21278.0,296199.0,2261703.0
3,00136b2bb7c74fa8fb5362311096d4d69d652064d1cca8...,1480.0,120013.0,1817713.0,22879.0,139461.0,1494199.0,22879.0,134932.0,555522.0,22879.0,139461.0,1494199.0,22879.0,134932.0,555522.0
4,001add687efe40428764e5e1e85ea13f94f1ac431b67c7...,2015.0,100898.0,1677582.0,18415.0,335548.0,415329.0,2015.0,100898.0,1677582.0,18415.0,252759.0,931871.0,2015.0,100898.0,1677582.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14858,ffef0bb8c8b21ffa989e460c774c1db7e5b1b47abd3ed7...,10488.0,23893.0,968080.0,9867.0,52676.0,723052.0,10488.0,296103.0,2283348.0,9867.0,52676.0,723052.0,23765.0,54545.0,1039963.0
14859,ffef318c5e1f4114ddf0225c0ae3f233b2ae2ff3ee4403...,49531.0,53115.0,1303569.0,20350.0,396234.0,211788.0,49531.0,53115.0,1303569.0,16169.0,115850.0,2030393.0,49531.0,53115.0,1303569.0
14860,fff0032cb902d90e0afd207446a2ff207b1b46e89b0482...,46299.0,166446.0,2724958.0,7427.0,18501.0,65699.0,7427.0,18501.0,1498464.0,7427.0,18501.0,65699.0,7427.0,18501.0,1498464.0
14861,fff4107e48a94c6a1fc884b78a93d8d194237840d7e656...,46849.0,363086.0,664882.0,30874.0,122063.0,1388441.0,46849.0,363086.0,664882.0,46849.0,266947.0,2600670.0,46849.0,363086.0,664882.0
14862,fffbcae1f0b7a651ad9ca6acbe35fd193aeafa2f9bc227...,881.0,389010.0,191878.0,881.0,389010.0,191878.0,881.0,389010.0,191878.0,881.0,389010.0,191878.0,881.0,389010.0,191878.0

In [631]:
res_geo.to_parquet('geo_last.parquet')

In [632]:
filtered_df

,client_id,target_1_new,target_2_new,target_3_new,target_1,target_2,target_3,target_4
0,00066ddb37c6a9cc8aef6404b3f485322501d6b2baefb4...,0,0,0,0.0,0.0,0.0,0.0
1,000757cdc288fb1095fa51b8f98166bc2d29bc5f6ea708...,0,0,0,0.0,0.0,0.0,0.0
2,000aa770a8067595eee038c07ba1b0ca1199e2114df5d6...,0,0,0,0.0,0.0,0.0,0.0
3,000d00eb3817aa52cc39c069f18cf7bf01444720a0c981...,0,0,1,0.0,0.0,0.0,0.0
4,000e054fc608075bb88aed7e08f6e7daf2510cf92388ae...,0,0,0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
28159,fffb5a08dfd1731d8a64ece41cb427249ae398e8ad684e...,0,0,0,0.0,0.0,0.0,0.0
28160,fffbcae1f0b7a651ad9ca6acbe35fd193aeafa2f9bc227...,0,0,0,0.0,0.0,0.0,0.0
28161,fffbf8fb4251ada84866d31e274634c8b2ab7400498e32...,0,0,0,0.0,0.0,0.0,0.0
28162,fffd127b61250edd960e8751b25f372d164e5cbb89761a...,0,0,0,0.0,0.0,0.0,0.0
28163,fffd1b037b3e6449de57d74e635021a3803e642a82dd2f...,0,0,0,0.0,0.0,0.0,0.0

In [633]:
res_geo

,client_id,geohash_4_1,geohash_5_1,geohash_6_1,geohash_4_2,geohash_5_2,geohash_6_2,geohash_4_3,geohash_5_3,geohash_6_3,geohash_4_4,geohash_5_4,geohash_6_4,geohash_4_5,geohash_5_5,geohash_6_5
0,00066ddb37c6a9cc8aef6404b3f485322501d6b2baefb4...,1201.0,207870.0,2621280.0,17422.0,253443.0,2093422.0,881.0,355868.0,2734460.0,17422.0,253443.0,2093422.0,881.0,355868.0,2734460.0
1,000d00eb3817aa52cc39c069f18cf7bf01444720a0c981...,17663.0,78557.0,1481635.0,48838.0,48705.0,1161521.0,22879.0,69963.0,139171.0,8773.0,339002.0,127224.0,27225.0,346893.0,777267.0
2,0011e86bf25a8ff48d4092b7d97450b8ab4eb807f69320...,5147.0,165006.0,1403192.0,21278.0,140231.0,217372.0,5147.0,165006.0,933687.0,21278.0,140231.0,217372.0,21278.0,296199.0,2261703.0
3,00136b2bb7c74fa8fb5362311096d4d69d652064d1cca8...,1480.0,120013.0,1817713.0,22879.0,139461.0,1494199.0,22879.0,134932.0,555522.0,22879.0,139461.0,1494199.0,22879.0,134932.0,555522.0
4,001add687efe40428764e5e1e85ea13f94f1ac431b67c7...,2015.0,100898.0,1677582.0,18415.0,335548.0,415329.0,2015.0,100898.0,1677582.0,18415.0,252759.0,931871.0,2015.0,100898.0,1677582.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14858,ffef0bb8c8b21ffa989e460c774c1db7e5b1b47abd3ed7...,10488.0,23893.0,968080.0,9867.0,52676.0,723052.0,10488.0,296103.0,2283348.0,9867.0,52676.0,723052.0,23765.0,54545.0,1039963.0
14859,ffef318c5e1f4114ddf0225c0ae3f233b2ae2ff3ee4403...,49531.0,53115.0,1303569.0,20350.0,396234.0,211788.0,49531.0,53115.0,1303569.0,16169.0,115850.0,2030393.0,49531.0,53115.0,1303569.0
14860,fff0032cb902d90e0afd207446a2ff207b1b46e89b0482...,46299.0,166446.0,2724958.0,7427.0,18501.0,65699.0,7427.0,18501.0,1498464.0,7427.0,18501.0,65699.0,7427.0,18501.0,1498464.0
14861,fff4107e48a94c6a1fc884b78a93d8d194237840d7e656...,46849.0,363086.0,664882.0,30874.0,122063.0,1388441.0,46849.0,363086.0,664882.0,46849.0,266947.0,2600670.0,46849.0,363086.0,664882.0
14862,fffbcae1f0b7a651ad9ca6acbe35fd193aeafa2f9bc227...,881.0,389010.0,191878.0,881.0,389010.0,191878.0,881.0,389010.0,191878.0,881.0,389010.0,191878.0,881.0,389010.0,191878.0

In [634]:
res_trx

,client_id,amount_1,event_type_1,currency_1,src_type11_1,src_type12_1,dst_type11_1,dst_type12_1,src_type21_1,src_type22_1,...,event_type_5,currency_5,src_type11_5,src_type12_5,dst_type11_5,dst_type12_5,src_type21_5,src_type22_5,src_type31_5,src_type32_5
0,00066ddb37c6a9cc8aef6404b3f485322501d6b2baefb4...,1.207451e+06,44,11,19,344,364,22652,3824,48,...,44.0,11.0,19.0,344.0,364.0,22652.0,3824.0,48.0,942.0,4.0
1,000757cdc288fb1095fa51b8f98166bc2d29bc5f6ea708...,4.103641e+03,37,11,19,902,433,10049,22294,72,...,37.0,11.0,19.0,902.0,433.0,10049.0,22294.0,72.0,1054.0,16.0
2,000d00eb3817aa52cc39c069f18cf7bf01444720a0c981...,2.768226e+03,38,11,19,344,813,20641,37565,70,...,38.0,11.0,19.0,344.0,813.0,20641.0,37565.0,70.0,522.0,55.0
3,0011e86bf25a8ff48d4092b7d97450b8ab4eb807f69320...,1.149264e+06,51,11,19,344,869,17340,11274,20,...,54.0,11.0,19.0,344.0,869.0,31488.0,11274.0,20.0,1037.0,2.0
4,00136b2bb7c74fa8fb5362311096d4d69d652064d1cca8...,1.480450e+02,54,11,19,344,364,22652,30151,70,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19131,fff4b0121e176fef8fd29b65d92a554ac5118d84deca79...,8.670344e+03,37,11,19,344,433,10049,42260,63,...,37.0,11.0,19.0,344.0,433.0,10049.0,42260.0,63.0,1825.0,26.0
19132,fff89e27c8947ce6beb0d915306b14db75ab50d94b9be4...,1.214823e+05,54,11,19,902,364,22652,15518,24,...,54.0,11.0,19.0,902.0,364.0,22652.0,15518.0,24.0,1835.0,26.0
19133,fffbcae1f0b7a651ad9ca6acbe35fd193aeafa2f9bc227...,1.580148e+03,37,11,19,344,433,10049,47714,48,...,37.0,11.0,19.0,344.0,433.0,10049.0,47714.0,48.0,2239.0,81.0
19134,fffd127b61250edd960e8751b25f372d164e5cbb89761a...,8.585744e-02,16,11,19,344,813,18723,26311,41,...,16.0,11.0,19.0,344.0,813.0,18723.0,26311.0,41.0,2468.0,4.0
19135,fffd1b037b3e6449de57d74e635021a3803e642a82dd2f...,6.012142e+03,37,11,19,344,433,10049,15373,70,...,37.0,11.0,19.0,344.0,433.0,10049.0,15373.0,70.0,1897.0,65.0

In [635]:
# Объединяем filtered_df с res_geo по client_id и mon
combined_df = pd.merge(filtered_df, res_geo, on=['client_id'], how='left')

# Объединяем полученный результат с res_trx по client_id и mon
combined_df = pd.merge(combined_df, res_trx, on=['client_id'], how='left')

# Замена всех NaN значений на 0 в итоговом DataFrame
combined_df = combined_df.fillna(0)

combined_df

,client_id,target_1_new,target_2_new,target_3_new,target_1,target_2,target_3,target_4,geohash_4_1,geohash_5_1,...,event_type_5,currency_5,src_type11_5,src_type12_5,dst_type11_5,dst_type12_5,src_type21_5,src_type22_5,src_type31_5,src_type32_5
0,00066ddb37c6a9cc8aef6404b3f485322501d6b2baefb4...,0,0,0,0.0,0.0,0.0,0.0,1201.0,207870.0,...,44.0,11.0,19.0,344.0,364.0,22652.0,3824.0,48.0,942.0,4.0
1,000757cdc288fb1095fa51b8f98166bc2d29bc5f6ea708...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,37.0,11.0,19.0,902.0,433.0,10049.0,22294.0,72.0,1054.0,16.0
2,000aa770a8067595eee038c07ba1b0ca1199e2114df5d6...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,000d00eb3817aa52cc39c069f18cf7bf01444720a0c981...,0,0,1,0.0,0.0,0.0,0.0,17663.0,78557.0,...,38.0,11.0,19.0,344.0,813.0,20641.0,37565.0,70.0,522.0,55.0
4,000e054fc608075bb88aed7e08f6e7daf2510cf92388ae...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28115,fffb5a08dfd1731d8a64ece41cb427249ae398e8ad684e...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28116,fffbcae1f0b7a651ad9ca6acbe35fd193aeafa2f9bc227...,0,0,0,0.0,0.0,0.0,0.0,881.0,389010.0,...,37.0,11.0,19.0,344.0,433.0,10049.0,47714.0,48.0,2239.0,81.0
28117,fffbf8fb4251ada84866d31e274634c8b2ab7400498e32...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28118,fffd127b61250edd960e8751b25f372d164e5cbb89761a...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.0,11.0,19.0,344.0,813.0,18723.0,26311.0,41.0,2468.0,4.0
28119,fffd1b037b3e6449de57d74e635021a3803e642a82dd2f...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,...,37.0,11.0,19.0,344.0,433.0,10049.0,15373.0,70.0,1897.0,65.0

In [636]:
combined_df.to_parquet('comb_last.parquet')

In [51]:
del filtered_df
del res_geo
del res_trx

In [47]:
%pip install torch pytorch-lightning pyarrow

Requirement already satisfied: torch in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (2.3.0)
Requirement already satisfied: pytorch-lightning in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (2.2.5)
Requirement already satisfied: pyarrow in c:\users\79045\appdata\local\programs\python\python311\lib\site-packages (14.0.1)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement memory-mapped-datasets (from versions: none)
ERROR: No matching distribution found for memory-mapped-datasets

In [6]:
import pandas as pd
import torch
import pytorch_lightning as pl
from torch.utils.data import DataLoader, Dataset
from pytorch_lightning import Trainer
from torch.nn import functional as F
from sklearn.preprocessing import StandardScaler, LabelEncoder
from functools import partial
import numpy as np

In [31]:
class TransactionDataset(Dataset):
    def __init__(self, data, client_col='client_id', period_col='period', target_cols=None):
        self.data = data
        self.client_col = client_col
        self.period_col = period_col
        self.target_cols = target_cols if target_cols else []

        self.clients = data[client_col].unique()
        self.data = self.data.sort_values(by=[client_col, period_col])
        
    def __len__(self):
        return len(self.clients)
    
    def __getitem__(self, idx):
        client_id = self.clients[idx]
        client_data = self.data[self.data[self.client_col] == client_id]
        
        features = []
        for i in range(1, len(client_data) + 1):
            monthly_data = client_data.iloc[:i].drop(columns=[self.client_col, self.period_col] + self.target_cols)
            features.append(monthly_data.values)
        
        targets = client_data[self.target_cols].values
        return torch.tensor(features, dtype=torch.float32), torch.tensor(targets, dtype=torch.float32), client_id

In [32]:
class EmbeddingModel(pl.LightningModule):
    def __init__(self, input_size, hidden_size, output_size, num_layers=2, dropout=0.1):
        super(EmbeddingModel, self).__init__()
        self.lstm = torch.nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, dropout=dropout if num_layers > 1 else 0.0)
        self.fc = torch.nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x_packed = torch.nn.utils.rnn.pack_sequence([torch.tensor(f) for f in x], enforce_sorted=False)
        lstm_out, (ht, ct) = self.lstm(x_packed)
        embeddings = self.fc(ht[-1])
        return embeddings

    def training_step(self, batch, batch_idx):
        x, y, _ = batch
        embeddings = self(x)
        loss = F.mse_loss(embeddings, y)
        self.log('train_loss', loss)
        return loss

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
        return optimizer

In [33]:
def train_model(data, input_size, hidden_size, output_size, num_layers=2, dropout=0.1, max_epochs=30):
    dataset = TransactionDataset(data, target_cols=['target_1', 'target_2', 'target_3', 'target_4'])
    
    train_size = int(0.8 * len(dataset))
    valid_size = len(dataset) - train_size
    train_dataset, valid_dataset = torch.utils.data.random_split(dataset, [train_size, valid_size])
    
    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=4)
    valid_loader = DataLoader(valid_dataset, batch_size=32, shuffle=False, num_workers=4)
    
    model = EmbeddingModel(input_size, hidden_size, output_size, num_layers, dropout)
    
    trainer = Trainer(max_epochs=max_epochs, accelerator='gpu' if torch.cuda.is_available() else 'cpu', devices=1 if torch.cuda.is_available() else 1, logger=False, enable_checkpointing=False)
    trainer.fit(model, train_loader, valid_loader)
    
    return model, trainer

In [34]:
def generate_embeddings(model, data, input_size):
    dataset = TransactionDataset(data, target_cols=['target_1', 'target_2', 'target_3', 'target_4'])
    data_loader = DataLoader(dataset, batch_size=32, shuffle=False, num_workers=4)
    
    embeddings = []
    client_ids = []

    for batch in data_loader:
        x, y, client_id = batch
        with torch.no_grad():
            embedding = model(x)
        embeddings.append(embedding.cpu().numpy())
        client_ids.extend(client_id.numpy())

    embeddings = np.concatenate(embeddings, axis=0)
    return pd.DataFrame(embeddings, index=client_ids, columns=[f'emb_{i}' for i in range(input_size)])

In [18]:
df  = pd.read_parquet('comb_1.parquet')

In [ ]:
# Пример использования

from sklearn.model_selection import train_test_split

    
input_size = df.shape[1] - 2 - 4  # Количество признаков минус client_id, period и 4 таргета
hidden_size = 256
output_size = 4  # Количество таргетов
    
model, trainer = train_model(df, input_size, hidden_size, output_size)
embeddings = generate_embeddings(model, df, hidden_size)
    
embeddings.to_csv('embeddings.csv', index=True)

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
C:\Users\79045\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytorch_lightning\trainer\configuration_validator.py:72: You passed in a `val_dataloader` but have no `validation_step`. Skipping val loop.

  | Name | Type   | Params
--------------------------------
0 | lstm | LSTM   | 11.9 M
1 | fc   | Linear | 1.0 K
--------------------------------
11.9 M    Trainable params
0         Non-trainable params
11.9 M    Total params
47.690    Total estimated model params size (MB)
C:\Users\79045\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:436: Consider setting `persistent_workers=True` in 'train_dataloader' to speed up the dataloader worker initialization.

In [637]:
import pandas as pd
import os

# Укажите путь к папке с файлами Parquet
folder_path = 'comb'

# Получите список всех файлов Parquet в папке
parquet_files = [f for f in os.listdir(folder_path) if f.endswith('.parquet')]

# Создайте пустой DataFrame для объединения данных
combined_df = pd.DataFrame()

# Прочитайте и объедините каждый файл Parquet
for file in parquet_files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_parquet(file_path)
    combined_df = pd.concat([combined_df, df], ignore_index=True)

In [698]:
combined_df.to_parquet('all.to_parquet')

In [639]:
# Подготовка данных
features = combined_df.drop(columns=['client_id', 'target_1', 'target_2', 'target_3', 'target_4'])
targets = combined_df[['target_1', 'target_2', 'target_3', 'target_4']]

In [649]:
client_ids = combined_df['client_id']

In [640]:
from catboost import CatBoostClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, accuracy_score

In [641]:
# Разделение данных на тренировочный и тестовый наборы
X_train, X_test, y_train, y_test = train_test_split(features, targets, test_size=0.2, random_state=42)

In [664]:
import optuna

In [642]:
# Создаем и обучаем модель
model = MultiOutputClassifier(CatBoostClassifier(iterations=100, learning_rate=0.1))
model.fit(X_train, y_train)

0:	learn: 0.4739745	total: 181ms	remaining: 18s
1:	learn: 0.3318163	total: 200ms	remaining: 9.82s
2:	learn: 0.2324480	total: 221ms	remaining: 7.16s
3:	learn: 0.1706504	total: 243ms	remaining: 5.84s
4:	learn: 0.1312541	total: 263ms	remaining: 4.99s
5:	learn: 0.1051868	total: 283ms	remaining: 4.43s
6:	learn: 0.0877589	total: 303ms	remaining: 4.03s
7:	learn: 0.0752914	total: 322ms	remaining: 3.7s
8:	learn: 0.0670549	total: 342ms	remaining: 3.46s
9:	learn: 0.0601003	total: 362ms	remaining: 3.26s
10:	learn: 0.0549695	total: 383ms	remaining: 3.1s
11:	learn: 0.0520592	total: 406ms	remaining: 2.98s
12:	learn: 0.0493712	total: 429ms	remaining: 2.87s
13:	learn: 0.0478385	total: 452ms	remaining: 2.77s
14:	learn: 0.0462482	total: 482ms	remaining: 2.73s
15:	learn: 0.0450294	total: 504ms	remaining: 2.65s
16:	learn: 0.0441268	total: 526ms	remaining: 2.57s
17:	learn: 0.0433898	total: 548ms	remaining: 2.5s
18:	learn: 0.0429139	total: 569ms	remaining: 2.42s
19:	learn: 0.0425661	total: 591ms	remaining: 2.36s
20:	learn: 0.0421704	total: 613ms	remaining: 2.3s
21:	learn: 0.0418215	total: 636ms	remaining: 2.26s
22:	learn: 0.0416159	total: 659ms	remaining: 2.21s
23:	learn: 0.0413857	total: 680ms	remaining: 2.15s
24:	learn: 0.0411978	total: 699ms	remaining: 2.1s
25:	learn: 0.0411018	total: 718ms	remaining: 2.04s
26:	learn: 0.0409012	total: 739ms	remaining: 2s
27:	learn: 0.0407903	total: 759ms	remaining: 1.95s
28:	learn: 0.0406682	total: 779ms	remaining: 1.91s
29:	learn: 0.0405838	total: 799ms	remaining: 1.86s
30:	learn: 0.0404830	total: 820ms	remaining: 1.82s
31:	learn: 0.0404164	total: 844ms	remaining: 1.79s
32:	learn: 0.0403767	total: 864ms	remaining: 1.75s
33:	learn: 0.0403191	total: 883ms	remaining: 1.71s
34:	learn: 0.0402575	total: 902ms	remaining: 1.67s
35:	learn: 0.0402114	total: 922ms	remaining: 1.64s
36:	learn: 0.0401481	total: 940ms	remaining: 1.6s
37:	learn: 0.0401114	total: 959ms	remaining: 1.56s
38:	learn: 0.0400729	total: 978ms	remaining: 1.53s
39:	learn: 0.0399693	total: 998ms	remaining: 1.5s
40:	learn: 0.0399051	total: 1.02s	remaining: 1.47s
41:	learn: 0.0398359	total: 1.04s	remaining: 1.44s
42:	learn: 0.0398010	total: 1.06s	remaining: 1.41s
43:	learn: 0.0397182	total: 1.08s	remaining: 1.38s
44:	learn: 0.0396478	total: 1.1s	remaining: 1.35s
45:	learn: 0.0396176	total: 1.12s	remaining: 1.32s
46:	learn: 0.0395585	total: 1.15s	remaining: 1.29s
47:	learn: 0.0395122	total: 1.17s	remaining: 1.26s
48:	learn: 0.0394706	total: 1.19s	remaining: 1.23s
49:	learn: 0.0394361	total: 1.21s	remaining: 1.21s
50:	learn: 0.0394096	total: 1.22s	remaining: 1.18s
51:	learn: 0.0393541	total: 1.25s	remaining: 1.15s
52:	learn: 0.0393320	total: 1.27s	remaining: 1.12s
53:	learn: 0.0392969	total: 1.29s	remaining: 1.1s
54:	learn: 0.0392496	total: 1.31s	remaining: 1.07s
55:	learn: 0.0391952	total: 1.33s	remaining: 1.04s
56:	learn: 0.0391193	total: 1.35s	remaining: 1.02s
57:	learn: 0.0390680	total: 1.37s	remaining: 990ms
58:	learn: 0.0390226	total: 1.39s	remaining: 964ms
59:	learn: 0.0390010	total: 1.41s	remaining: 938ms
60:	learn: 0.0389866	total: 1.43s	remaining: 912ms
61:	learn: 0.0389548	total: 1.45s	remaining: 886ms
62:	learn: 0.0388803	total: 1.47s	remaining: 862ms
63:	learn: 0.0388078	total: 1.49s	remaining: 838ms
64:	learn: 0.0387786	total: 1.51s	remaining: 812ms
65:	learn: 0.0387457	total: 1.53s	remaining: 787ms
66:	learn: 0.0386947	total: 1.55s	remaining: 762ms
67:	learn: 0.0386492	total: 1.56s	remaining: 737ms
68:	learn: 0.0385649	total: 1.58s	remaining: 712ms
69:	learn: 0.0385174	total: 1.6s	remaining: 688ms
70:	learn: 0.0384667	total: 1.63s	remaining: 664ms
71:	learn: 0.0384503	total: 1.65s	remaining: 640ms
72:	learn: 0.0384299	total: 1.67s	remaining: 618ms
73:	learn: 0.0383385	total: 1.69s	remaining: 595ms
74:	learn: 0.0382842	total: 1.72s	remaining: 572ms
75:	learn: 0.0382469	total: 1.74s	remaining: 549ms
76:	learn: 0.0381580	total: 1.76s	remaining: 526ms
77:	learn: 0.0381042	total: 1.79s	remaining: 504ms
78:	learn: 0.0380588	total: 1.81s	remaining: 482ms
79:	learn: 0.0380427	total: 1.83s	remaining: 458ms
80:	learn: 0.0379756	total: 1.85s	remaining: 435ms
81:	learn: 0.0379654	total: 1.87s	remaining: 411ms
82:	learn: 0.0378974	total: 1.89s	remaining: 388ms
83:	learn: 0.0378327	total: 1.92s	remaining: 365ms
84:	learn: 0.0378104	total: 1.94s	remaining: 342ms
85:	learn: 0.0377396	total: 1.96s	remaining: 319ms
86:	learn: 0.0377046	total: 1.98s	remaining: 296ms
87:	learn: 0.0376643	total: 2s	remaining: 272ms
88:	learn: 0.0376271	total: 2.02s	remaining: 249ms
89:	learn: 0.0376061	total: 2.04s	remaining: 226ms
90:	learn: 0.0375480	total: 2.06s	remaining: 204ms
91:	learn: 0.0375203	total: 2.08s	remaining: 181ms
92:	learn: 0.0374968	total: 2.1s	remaining: 158ms
93:	learn: 0.0374822	total: 2.12s	remaining: 135ms
94:	learn: 0.0374363	total: 2.14s	remaining: 113ms
95:	learn: 0.0373743	total: 2.16s	remaining: 90.1ms
96:	learn: 0.0373327	total: 2.18s	remaining: 67.5ms
97:	learn: 0.0373145	total: 2.2s	remaining: 45ms
98:	learn: 0.0372650	total: 2.22s	remaining: 22.5ms
99:	learn: 0.0372191	total: 2.24s	remaining: 0us
0:	learn: 0.3935081	total: 23.7ms	remaining: 2.35s
1:	learn: 0.2295067	total: 42.9ms	remaining: 2.1s
2:	learn: 0.1387012	total: 64.2ms	remaining: 2.08s
3:	learn: 0.0884694	total: 86.4ms	remaining: 2.07s
4:	learn: 0.0597947	total: 109ms	remaining: 2.07s
5:	learn: 0.0424629	total: 132ms	remaining: 2.06s
6:	learn: 0.0315582	total: 154ms	remaining: 2.05s
7:	learn: 0.0238383	total: 178ms	remaining: 2.04s
8:	learn: 0.0189860	total: 199ms	remaining: 2.02s
9:	learn: 0.0157070	total: 221ms	remaining: 1.99s
10:	learn: 0.0136019	total: 242ms	remaining: 1.96s
11:	learn: 0.0123181	total: 264ms	remaining: 1.93s
12:	learn: 0.0114358	total: 287ms	remaining: 1.92s
13:	learn: 0.0105855	total: 308ms	remaining: 1.89s
14:	learn: 0.0099606	total: 328ms	remaining: 1.86s
15:	learn: 0.0094839	total: 348ms	remaining: 1.82s
16:	learn: 0.0091364	total: 369ms	remaining: 1.8s
17:	learn: 0.0089116	total: 390ms	remaining: 1.78s
18:	learn: 0.0086729	total: 412ms	remaining: 1.75s
19:	learn: 0.0084938	total: 430ms	remaining: 1.72s
20:	learn: 0.0083328	total: 450ms	remaining: 1.69s
21:	learn: 0.0082187	total: 472ms	remaining: 1.67s
22:	learn: 0.0081303	total: 493ms	remaining: 1.65s
23:	learn: 0.0080269	total: 512ms	remaining: 1.62s
24:	learn: 0.0079522	total: 532ms	remaining: 1.59s
25:	learn: 0.0078816	total: 550ms	remaining: 1.56s
26:	learn: 0.0078197	total: 569ms	remaining: 1.54s
27:	learn: 0.0077796	total: 587ms	remaining: 1.51s
28:	learn: 0.0077423	total: 605ms	remaining: 1.48s
29:	learn: 0.0077033	total: 625ms	remaining: 1.46s
30:	learn: 0.0076708	total: 643ms	remaining: 1.43s
31:	learn: 0.0076441	total: 664ms	remaining: 1.41s
32:	learn: 0.0076067	total: 683ms	remaining: 1.39s
33:	learn: 0.0075911	total: 704ms	remaining: 1.37s
34:	learn: 0.0075490	total: 725ms	remaining: 1.35s
35:	learn: 0.0075265	total: 744ms	remaining: 1.32s
36:	learn: 0.0075114	total: 764ms	remaining: 1.3s
37:	learn: 0.0074698	total: 783ms	remaining: 1.28s
38:	learn: 0.0074272	total: 803ms	remaining: 1.25s
39:	learn: 0.0073967	total: 822ms	remaining: 1.23s
40:	learn: 0.0073745	total: 841ms	remaining: 1.21s
41:	learn: 0.0073547	total: 860ms	remaining: 1.19s
42:	learn: 0.0073379	total: 880ms	remaining: 1.17s
43:	learn: 0.0073251	total: 900ms	remaining: 1.15s
44:	learn: 0.0073146	total: 919ms	remaining: 1.12s
45:	learn: 0.0072859	total: 940ms	remaining: 1.1s
46:	learn: 0.0072760	total: 959ms	remaining: 1.08s
47:	learn: 0.0072699	total: 978ms	remaining: 1.06s
48:	learn: 0.0072560	total: 995ms	remaining: 1.03s
49:	learn: 0.0072387	total: 1.01s	remaining: 1.01s
50:	learn: 0.0072309	total: 1.03s	remaining: 993ms
51:	learn: 0.0072154	total: 1.05s	remaining: 971ms
52:	learn: 0.0072040	total: 1.07s	remaining: 950ms
53:	learn: 0.0071932	total: 1.09s	remaining: 928ms
54:	learn: 0.0071708	total: 1.11s	remaining: 908ms
55:	learn: 0.0071546	total: 1.13s	remaining: 886ms
56:	learn: 0.0071381	total: 1.15s	remaining: 864ms
57:	learn: 0.0071000	total: 1.16s	remaining: 843ms
58:	learn: 0.0070792	total: 1.18s	remaining: 822ms
59:	learn: 0.0070602	total: 1.2s	remaining: 803ms
60:	learn: 0.0070498	total: 1.22s	remaining: 783ms
61:	learn: 0.0070250	total: 1.24s	remaining: 763ms
62:	learn: 0.0070076	total: 1.26s	remaining: 743ms
63:	learn: 0.0069959	total: 1.28s	remaining: 723ms
64:	learn: 0.0069819	total: 1.3s	remaining: 702ms
65:	learn: 0.0069673	total: 1.32s	remaining: 683ms
66:	learn: 0.0069470	total: 1.34s	remaining: 662ms
67:	learn: 0.0069329	total: 1.36s	remaining: 641ms
68:	learn: 0.0069027	total: 1.39s	remaining: 623ms
69:	learn: 0.0068917	total: 1.41s	remaining: 602ms
70:	learn: 0.0068785	total: 1.43s	remaining: 582ms
71:	learn: 0.0068718	total: 1.45s	remaining: 563ms
72:	learn: 0.0068437	total: 1.47s	remaining: 543ms
73:	learn: 0.0068397	total: 1.49s	remaining: 523ms
74:	learn: 0.0068259	total: 1.51s	remaining: 503ms
75:	learn: 0.0068168	total: 1.53s	remaining: 483ms
76:	learn: 0.0068093	total: 1.55s	remaining: 463ms
77:	learn: 0.0067891	total: 1.57s	remaining: 443ms
78:	learn: 0.0067827	total: 1.59s	remaining: 423ms
79:	learn: 0.0067709	total: 1.61s	remaining: 403ms
80:	learn: 0.0067649	total: 1.63s	remaining: 383ms
81:	learn: 0.0067533	total: 1.65s	remaining: 362ms
82:	learn: 0.0067452	total: 1.67s	remaining: 342ms
83:	learn: 0.0067302	total: 1.69s	remaining: 322ms
84:	learn: 0.0067222	total: 1.71s	remaining: 303ms
85:	learn: 0.0067124	total: 1.73s	remaining: 282ms
86:	learn: 0.0067020	total: 1.75s	remaining: 262ms
87:	learn: 0.0066901	total: 1.77s	remaining: 242ms
88:	learn: 0.0066824	total: 1.79s	remaining: 222ms
89:	learn: 0.0066566	total: 1.81s	remaining: 202ms
90:	learn: 0.0066476	total: 1.83s	remaining: 181ms
91:	learn: 0.0066407	total: 1.85s	remaining: 161ms
92:	learn: 0.0066336	total: 1.87s	remaining: 141ms
93:	learn: 0.0066219	total: 1.89s	remaining: 121ms
94:	learn: 0.0066132	total: 1.91s	remaining: 101ms
95:	learn: 0.0065916	total: 1.93s	remaining: 80.5ms
96:	learn: 0.0065839	total: 1.95s	remaining: 60.3ms
97:	learn: 0.0065616	total: 1.97s	remaining: 40.2ms
98:	learn: 0.0065517	total: 1.99s	remaining: 20.1ms
99:	learn: 0.0065422	total: 2.01s	remaining: 0us
0:	learn: 0.4448277	total: 21.8ms	remaining: 2.16s
1:	learn: 0.2983648	total: 42.6ms	remaining: 2.09s
2:	learn: 0.2049234	total: 64.7ms	remaining: 2.09s
3:	learn: 0.1493920	total: 85.6ms	remaining: 2.06s
4:	learn: 0.1147014	total: 106ms	remaining: 2.01s
5:	learn: 0.0925363	total: 127ms	remaining: 1.98s
6:	learn: 0.0776098	total: 147ms	remaining: 1.95s
7:	learn: 0.0673907	total: 167ms	remaining: 1.92s
8:	learn: 0.0599858	total: 188ms	remaining: 1.9s
9:	learn: 0.0542482	total: 208ms	remaining: 1.87s
10:	learn: 0.0505208	total: 232ms	remaining: 1.88s
11:	learn: 0.0476505	total: 254ms	remaining: 1.86s
12:	learn: 0.0452608	total: 289ms	remaining: 1.94s
13:	learn: 0.0437200	total: 310ms	remaining: 1.9s
14:	learn: 0.0422628	total: 332ms	remaining: 1.88s
15:	learn: 0.0413024	total: 353ms	remaining: 1.85s
16:	learn: 0.0406335	total: 374ms	remaining: 1.83s
17:	learn: 0.0398772	total: 396ms	remaining: 1.8s
18:	learn: 0.0394437	total: 418ms	remaining: 1.78s
19:	learn: 0.0390148	total: 441ms	remaining: 1.76s
20:	learn: 0.0386035	total: 464ms	remaining: 1.74s
21:	learn: 0.0383825	total: 488ms	remaining: 1.73s
22:	learn: 0.0380698	total: 537ms	remaining: 1.8s
23:	learn: 0.0378553	total: 577ms	remaining: 1.83s
24:	learn: 0.0376834	total: 599ms	remaining: 1.8s
25:	learn: 0.0375190	total: 619ms	remaining: 1.76s
26:	learn: 0.0373950	total: 639ms	remaining: 1.73s
27:	learn: 0.0372184	total: 660ms	remaining: 1.7s
28:	learn: 0.0371094	total: 681ms	remaining: 1.67s
29:	learn: 0.0369247	total: 703ms	remaining: 1.64s
30:	learn: 0.0368246	total: 724ms	remaining: 1.61s
31:	learn: 0.0367255	total: 746ms	remaining: 1.58s
32:	learn: 0.0366386	total: 768ms	remaining: 1.56s
33:	learn: 0.0366098	total: 788ms	remaining: 1.53s
34:	learn: 0.0364854	total: 809ms	remaining: 1.5s
35:	learn: 0.0364200	total: 828ms	remaining: 1.47s
36:	learn: 0.0363490	total: 849ms	remaining: 1.45s
37:	learn: 0.0362983	total: 869ms	remaining: 1.42s
38:	learn: 0.0362515	total: 886ms	remaining: 1.39s
39:	learn: 0.0361255	total: 908ms	remaining: 1.36s
40:	learn: 0.0360933	total: 929ms	remaining: 1.34s
41:	learn: 0.0360459	total: 949ms	remaining: 1.31s
42:	learn: 0.0359607	total: 969ms	remaining: 1.28s
43:	learn: 0.0359099	total: 987ms	remaining: 1.25s
44:	learn: 0.0358728	total: 1s	remaining: 1.23s
45:	learn: 0.0357771	total: 1.03s	remaining: 1.21s
46:	learn: 0.0357512	total: 1.04s	remaining: 1.18s
47:	learn: 0.0357265	total: 1.06s	remaining: 1.15s
48:	learn: 0.0356764	total: 1.08s	remaining: 1.13s
49:	learn: 0.0356456	total: 1.1s	remaining: 1.1s
50:	learn: 0.0356080	total: 1.12s	remaining: 1.08s
51:	learn: 0.0355646	total: 1.14s	remaining: 1.05s
52:	learn: 0.0355472	total: 1.16s	remaining: 1.03s
53:	learn: 0.0355203	total: 1.18s	remaining: 1s
54:	learn: 0.0354891	total: 1.2s	remaining: 981ms
55:	learn: 0.0354710	total: 1.22s	remaining: 959ms
56:	learn: 0.0354438	total: 1.24s	remaining: 933ms
57:	learn: 0.0354161	total: 1.25s	remaining: 909ms
58:	learn: 0.0353828	total: 1.27s	remaining: 885ms
59:	learn: 0.0353550	total: 1.29s	remaining: 860ms
60:	learn: 0.0353034	total: 1.31s	remaining: 838ms
61:	learn: 0.0352741	total: 1.33s	remaining: 816ms
62:	learn: 0.0352575	total: 1.35s	remaining: 794ms
63:	learn: 0.0352035	total: 1.37s	remaining: 773ms
64:	learn: 0.0351830	total: 1.39s	remaining: 750ms
65:	learn: 0.0351478	total: 1.41s	remaining: 727ms
66:	learn: 0.0351028	total: 1.43s	remaining: 705ms
67:	learn: 0.0350741	total: 1.45s	remaining: 683ms
68:	learn: 0.0349928	total: 1.47s	remaining: 661ms
69:	learn: 0.0349605	total: 1.49s	remaining: 640ms
70:	learn: 0.0348774	total: 1.52s	remaining: 620ms
71:	learn: 0.0348339	total: 1.54s	remaining: 599ms
72:	learn: 0.0347887	total: 1.56s	remaining: 579ms
73:	learn: 0.0347687	total: 1.58s	remaining: 557ms
74:	learn: 0.0347447	total: 1.6s	remaining: 535ms
75:	learn: 0.0346913	total: 1.63s	remaining: 514ms
76:	learn: 0.0346451	total: 1.65s	remaining: 492ms
77:	learn: 0.0346094	total: 1.67s	remaining: 471ms
78:	learn: 0.0345657	total: 1.69s	remaining: 450ms
79:	learn: 0.0345466	total: 1.71s	remaining: 428ms
80:	learn: 0.0344996	total: 1.73s	remaining: 406ms
81:	learn: 0.0344411	total: 1.75s	remaining: 385ms
82:	learn: 0.0344110	total: 1.78s	remaining: 364ms
83:	learn: 0.0343638	total: 1.8s	remaining: 343ms
84:	learn: 0.0343077	total: 1.82s	remaining: 321ms
85:	learn: 0.0342473	total: 1.84s	remaining: 300ms
86:	learn: 0.0342375	total: 1.86s	remaining: 278ms
87:	learn: 0.0342211	total: 1.88s	remaining: 256ms
88:	learn: 0.0341854	total: 1.9s	remaining: 235ms
89:	learn: 0.0341268	total: 1.92s	remaining: 213ms
90:	learn: 0.0341142	total: 1.94s	remaining: 192ms
91:	learn: 0.0340628	total: 1.96s	remaining: 170ms
92:	learn: 0.0340042	total: 1.98s	remaining: 149ms
93:	learn: 0.0339612	total: 2s	remaining: 128ms
94:	learn: 0.0339057	total: 2.02s	remaining: 106ms
95:	learn: 0.0338613	total: 2.04s	remaining: 85ms
96:	learn: 0.0338513	total: 2.06s	remaining: 63.7ms
97:	learn: 0.0338159	total: 2.08s	remaining: 42.5ms
98:	learn: 0.0337657	total: 2.1s	remaining: 21.3ms
99:	learn: 0.0337416	total: 2.13s	remaining: 0us
0:	learn: 0.4531627	total: 24.5ms	remaining: 2.43s
1:	learn: 0.3057511	total: 45.7ms	remaining: 2.24s
2:	learn: 0.2105997	total: 69.6ms	remaining: 2.25s
3:	learn: 0.1532894	total: 91.9ms	remaining: 2.21s
4:	learn: 0.1171218	total: 112ms	remaining: 2.14s
5:	learn: 0.0935391	total: 134ms	remaining: 2.09s
6:	learn: 0.0770817	total: 155ms	remaining: 2.05s
7:	learn: 0.0664242	total: 175ms	remaining: 2.01s
8:	learn: 0.0591734	total: 196ms	remaining: 1.98s
9:	learn: 0.0534853	total: 217ms	remaining: 1.96s
10:	learn: 0.0497282	total: 240ms	remaining: 1.94s
11:	learn: 0.0468968	total: 265ms	remaining: 1.94s
12:	learn: 0.0444259	total: 286ms	remaining: 1.91s
13:	learn: 0.0425959	total: 306ms	remaining: 1.88s
14:	learn: 0.0410925	total: 327ms	remaining: 1.85s
15:	learn: 0.0400055	total: 348ms	remaining: 1.83s
16:	learn: 0.0393766	total: 368ms	remaining: 1.8s
17:	learn: 0.0386383	total: 390ms	remaining: 1.78s
18:	learn: 0.0381126	total: 409ms	remaining: 1.74s
19:	learn: 0.0377535	total: 430ms	remaining: 1.72s
20:	learn: 0.0372744	total: 452ms	remaining: 1.7s
21:	learn: 0.0369638	total: 473ms	remaining: 1.68s
22:	learn: 0.0367498	total: 494ms	remaining: 1.66s
23:	learn: 0.0366168	total: 514ms	remaining: 1.63s
24:	learn: 0.0363741	total: 534ms	remaining: 1.6s
25:	learn: 0.0362161	total: 553ms	remaining: 1.57s
26:	learn: 0.0361314	total: 572ms	remaining: 1.55s
27:	learn: 0.0360014	total: 592ms	remaining: 1.52s
28:	learn: 0.0358424	total: 613ms	remaining: 1.5s
29:	learn: 0.0357745	total: 632ms	remaining: 1.48s
30:	learn: 0.0355517	total: 654ms	remaining: 1.46s
31:	learn: 0.0354391	total: 673ms	remaining: 1.43s
32:	learn: 0.0353171	total: 696ms	remaining: 1.41s
33:	learn: 0.0352898	total: 715ms	remaining: 1.39s
34:	learn: 0.0351295	total: 735ms	remaining: 1.36s
35:	learn: 0.0349817	total: 756ms	remaining: 1.34s
36:	learn: 0.0349658	total: 775ms	remaining: 1.32s
37:	learn: 0.0349341	total: 794ms	remaining: 1.3s
38:	learn: 0.0347566	total: 815ms	remaining: 1.27s
39:	learn: 0.0346574	total: 836ms	remaining: 1.25s
40:	learn: 0.0346262	total: 856ms	remaining: 1.23s
41:	learn: 0.0345910	total: 877ms	remaining: 1.21s
42:	learn: 0.0344571	total: 902ms	remaining: 1.2s
43:	learn: 0.0343444	total: 925ms	remaining: 1.18s
44:	learn: 0.0342807	total: 947ms	remaining: 1.16s
45:	learn: 0.0341818	total: 966ms	remaining: 1.13s
46:	learn: 0.0340828	total: 987ms	remaining: 1.11s
47:	learn: 0.0340488	total: 1.01s	remaining: 1.09s
48:	learn: 0.0339469	total: 1.03s	remaining: 1.07s
49:	learn: 0.0338279	total: 1.05s	remaining: 1.05s
50:	learn: 0.0337016	total: 1.08s	remaining: 1.03s
51:	learn: 0.0336648	total: 1.1s	remaining: 1.01s
52:	learn: 0.0336191	total: 1.12s	remaining: 994ms
53:	learn: 0.0335511	total: 1.14s	remaining: 972ms
54:	learn: 0.0335272	total: 1.16s	remaining: 950ms
55:	learn: 0.0334185	total: 1.18s	remaining: 929ms
56:	learn: 0.0333806	total: 1.2s	remaining: 907ms
57:	learn: 0.0333120	total: 1.22s	remaining: 886ms
58:	learn: 0.0332508	total: 1.25s	remaining: 867ms
59:	learn: 0.0331873	total: 1.27s	remaining: 846ms
60:	learn: 0.0331117	total: 1.29s	remaining: 824ms
61:	learn: 0.0329942	total: 1.31s	remaining: 804ms
62:	learn: 0.0329724	total: 1.33s	remaining: 783ms
63:	learn: 0.0329066	total: 1.36s	remaining: 763ms
64:	learn: 0.0328402	total: 1.38s	remaining: 742ms
65:	learn: 0.0328032	total: 1.4s	remaining: 721ms
66:	learn: 0.0327668	total: 1.42s	remaining: 699ms
67:	learn: 0.0327395	total: 1.44s	remaining: 677ms
68:	learn: 0.0326802	total: 1.46s	remaining: 655ms
69:	learn: 0.0326293	total: 1.48s	remaining: 633ms
70:	learn: 0.0326043	total: 1.5s	remaining: 612ms
71:	learn: 0.0325323	total: 1.52s	remaining: 591ms
72:	learn: 0.0324849	total: 1.54s	remaining: 570ms
73:	learn: 0.0324245	total: 1.56s	remaining: 550ms
74:	learn: 0.0323390	total: 1.58s	remaining: 528ms
75:	learn: 0.0322999	total: 1.6s	remaining: 507ms
76:	learn: 0.0322582	total: 1.62s	remaining: 485ms
77:	learn: 0.0321985	total: 1.65s	remaining: 464ms
78:	learn: 0.0321299	total: 1.67s	remaining: 443ms
79:	learn: 0.0320889	total: 1.68s	remaining: 421ms
80:	learn: 0.0320508	total: 1.7s	remaining: 400ms
81:	learn: 0.0320180	total: 1.72s	remaining: 378ms
82:	learn: 0.0319793	total: 1.75s	remaining: 357ms
83:	learn: 0.0319492	total: 1.77s	remaining: 337ms
84:	learn: 0.0319036	total: 1.79s	remaining: 316ms
85:	learn: 0.0318610	total: 1.81s	remaining: 295ms
86:	learn: 0.0317842	total: 1.83s	remaining: 274ms
87:	learn: 0.0317508	total: 1.85s	remaining: 253ms
88:	learn: 0.0317120	total: 1.87s	remaining: 232ms
89:	learn: 0.0316160	total: 1.89s	remaining: 210ms
90:	learn: 0.0315597	total: 1.91s	remaining: 189ms
91:	learn: 0.0315066	total: 1.93s	remaining: 168ms
92:	learn: 0.0314770	total: 1.95s	remaining: 147ms

MultiOutputClassifier(estimator=<catboost.core.CatBoostClassifier object at 0x0000025B241F3E10>)

In [643]:
# Оценка производительности моделей с использованием ROC-AUC и accuracy
roc_auc_scores = {}
accuracy_scores = {}
for i, target in enumerate(targets.columns):
    y_pred = model.predict(X_test)[:, i]
    accuracy = accuracy_score(y_test[target], y_pred)
    accuracy_scores[target] = accuracy
    print(f'Accuracy for {target}: {accuracy}')
    
    if len(y_test[target].unique()) == 2:  # Проверка на наличие двух классов
        y_pred_proba = model.estimators_[i].predict_proba(X_test)[:, 1]  # Получение вероятностей для положительного класса
        roc_auc = roc_auc_score(y_test[target], y_pred_proba)
        roc_auc_scores[target] = roc_auc
        print(f'ROC-AUC for {target}: {roc_auc}')
    else:
        print(f'ROC-AUC for {target} is not defined due to only one class present in y_test.')
        roc_auc_scores[target] = None

Accuracy for target_1: 0.9908534415260872
ROC-AUC for target_1: 0.8081384046175497
Accuracy for target_2: 0.9987543597409069
ROC-AUC for target_2: 0.8623026761215836
Accuracy for target_3: 0.9932023631575201
ROC-AUC for target_3: 0.8054379195521699
Accuracy for target_4: 0.9927041070538828
ROC-AUC for target_4: 0.8617915326251101

In [644]:
# Пример использования обученной модели
example_data = X_test.iloc[0:1]  # Взять одну строку из тестового набора для примера
predictions = model.predict(example_data)
for i, target in enumerate(targets.columns):
    print(f'Prediction for {target}: {predictions[0, i]}')

Prediction for target_1: 0.0
Prediction for target_2: 0.0
Prediction for target_3: 0.0
Prediction for target_4: 0.0

In [705]:
df = pd.read_csv("sample_submission.csv",index_col=None)
df

,Unnamed: 0,client_id,target_1,target_2,target_3,target_4
0,0,2b7ff0c1c99cefe259ed83c5dfa0a403f2cbc88032b671...,0.001422,0.000176,0.088572,0.003422
1,1,0433d23e224b7a520656da6181efadb8d556bb293158c9...,0.014299,0.000435,0.010419,0.003007
2,2,f2ce8b292e5f9f778f3e20db7608ac76dc8812113a2631...,0.017853,0.007523,0.010701,0.021349
3,3,4f807e8b163c653bcaeff9f925983568f4c3e6b1a1f231...,0.010975,0.004356,0.025208,0.026687
4,4,64369f6f8ae1b719332ee1bfb2b454e642b2053d2c9b8a...,0.010453,0.000531,0.010711,0.001758
...,...,...,...,...,...,...
140483,140483,d49a66825bb16ceb5b6a01126e1f2391b085dba8da44ee...,0.010042,0.002497,0.017207,0.007788
140484,140484,f772af6720c0b591d49b97946c5e420c1c077affc0f7c7...,0.008701,0.000476,0.004393,0.016346
140485,140485,06b282335bc4853f888e1ab50a6ba23a8e420d42313959...,0.009764,0.002151,0.010213,0.002264
140486,140486,90d423a25d7cdaf674f7d78bc37d88830443ff17717e02...,0.016902,0.000972,0.014184,0.037340
140487,140487,f63e55b226d3732b8b4927be8a2cdc7fb88ff2bb0561e2...,0.007528,0.000687,0.004786,0.004292

In [701]:
# Предсказания
probas = model.predict_proba(features)

proba_df = pd.DataFrame({
    'client_id': client_ids,
    'target_1': [proba[:, 1] for proba in probas][0],
    'target_2': [proba[:, 1] for proba in probas][1],
    'target_3': [proba[:, 1] for proba in probas][2],
    'target_4': [proba[:, 1] for proba in probas][3]
})

In [712]:
proba_df['target_1'][3]

0.00024572140573265734

In [714]:
proba_df.to_csv('test.csv', index=False)

In [715]:
df = pd.read_csv("sample_submission.csv",index_col=0)
df

,client_id,target_1,target_2,target_3,target_4
0,2b7ff0c1c99cefe259ed83c5dfa0a403f2cbc88032b671...,0.001422,0.000176,0.088572,0.003422
1,0433d23e224b7a520656da6181efadb8d556bb293158c9...,0.014299,0.000435,0.010419,0.003007
2,f2ce8b292e5f9f778f3e20db7608ac76dc8812113a2631...,0.017853,0.007523,0.010701,0.021349
3,4f807e8b163c653bcaeff9f925983568f4c3e6b1a1f231...,0.010975,0.004356,0.025208,0.026687
4,64369f6f8ae1b719332ee1bfb2b454e642b2053d2c9b8a...,0.010453,0.000531,0.010711,0.001758
...,...,...,...,...,...
140483,d49a66825bb16ceb5b6a01126e1f2391b085dba8da44ee...,0.010042,0.002497,0.017207,0.007788
140484,f772af6720c0b591d49b97946c5e420c1c077affc0f7c7...,0.008701,0.000476,0.004393,0.016346
140485,06b282335bc4853f888e1ab50a6ba23a8e420d42313959...,0.009764,0.002151,0.010213,0.002264
140486,90d423a25d7cdaf674f7d78bc37d88830443ff17717e02...,0.016902,0.000972,0.014184,0.037340
140487,f63e55b226d3732b8b4927be8a2cdc7fb88ff2bb0561e2...,0.007528,0.000687,0.004786,0.004292

In [713]:
df['target_1'][3]

0.0109747057385375

In [716]:
merged_df = df[['client_id']].merge(proba_df, on='client_id', how='left')

In [718]:
merged_df

,client_id,target_1,target_2,target_3,target_4
0,2b7ff0c1c99cefe259ed83c5dfa0a403f2cbc88032b671...,0.000896,0.000532,0.018979,0.000897
1,0433d23e224b7a520656da6181efadb8d556bb293158c9...,0.012424,0.001142,0.008384,0.007694
2,f2ce8b292e5f9f778f3e20db7608ac76dc8812113a2631...,0.000388,0.000061,0.000235,0.000322
3,4f807e8b163c653bcaeff9f925983568f4c3e6b1a1f231...,0.009245,0.002301,0.014516,0.044771
4,64369f6f8ae1b719332ee1bfb2b454e642b2053d2c9b8a...,0.001565,0.002644,0.004672,0.001629
...,...,...,...,...,...
140483,d49a66825bb16ceb5b6a01126e1f2391b085dba8da44ee...,0.006169,0.000801,0.011587,0.002164
140484,f772af6720c0b591d49b97946c5e420c1c077affc0f7c7...,0.007472,0.000856,0.004972,0.031333
140485,06b282335bc4853f888e1ab50a6ba23a8e420d42313959...,0.024726,0.001455,0.006492,0.001291
140486,90d423a25d7cdaf674f7d78bc37d88830443ff17717e02...,0.039168,0.001116,0.020141,0.017312
140487,f63e55b226d3732b8b4927be8a2cdc7fb88ff2bb0561e2...,0.005211,0.001137,0.003752,0.004526

In [719]:
df

,client_id,target_1,target_2,target_3,target_4
0,2b7ff0c1c99cefe259ed83c5dfa0a403f2cbc88032b671...,0.001422,0.000176,0.088572,0.003422
1,0433d23e224b7a520656da6181efadb8d556bb293158c9...,0.014299,0.000435,0.010419,0.003007
2,f2ce8b292e5f9f778f3e20db7608ac76dc8812113a2631...,0.017853,0.007523,0.010701,0.021349
3,4f807e8b163c653bcaeff9f925983568f4c3e6b1a1f231...,0.010975,0.004356,0.025208,0.026687
4,64369f6f8ae1b719332ee1bfb2b454e642b2053d2c9b8a...,0.010453,0.000531,0.010711,0.001758
...,...,...,...,...,...
140483,d49a66825bb16ceb5b6a01126e1f2391b085dba8da44ee...,0.010042,0.002497,0.017207,0.007788
140484,f772af6720c0b591d49b97946c5e420c1c077affc0f7c7...,0.008701,0.000476,0.004393,0.016346
140485,06b282335bc4853f888e1ab50a6ba23a8e420d42313959...,0.009764,0.002151,0.010213,0.002264
140486,90d423a25d7cdaf674f7d78bc37d88830443ff17717e02...,0.016902,0.000972,0.014184,0.037340
140487,f63e55b226d3732b8b4927be8a2cdc7fb88ff2bb0561e2...,0.007528,0.000687,0.004786,0.004292

In [722]:
merged_df.to_csv('last.csv',index=False)

In [674]:
df['target_1'] = merged_df['target_1_proba']
df['target_2'] = merged_df['target_2_proba']
df['target_3'] = merged_df['target_3_proba']
df['target_4'] = merged_df['target_4_proba']

In [677]:
df = df.drop(columns = ['Unnamed: 0'])

In [688]:
l = l.rename(columns={'Unnamed: 0': ''})

In [695]:
l

,Unnamed: 0,client_id,target_1,target_2,target_3,target_4
0,0,2b7ff0c1c99cefe259ed83c5dfa0a403f2cbc88032b671...,0.000896,0.000532,0.018979,0.000897
1,1,0433d23e224b7a520656da6181efadb8d556bb293158c9...,0.012424,0.001142,0.008384,0.007694
2,2,f2ce8b292e5f9f778f3e20db7608ac76dc8812113a2631...,0.000388,0.000061,0.000235,0.000322
3,3,4f807e8b163c653bcaeff9f925983568f4c3e6b1a1f231...,0.009245,0.002301,0.014516,0.044771
4,4,64369f6f8ae1b719332ee1bfb2b454e642b2053d2c9b8a...,0.001565,0.002644,0.004672,0.001629
...,...,...,...,...,...,...
140483,140483,d49a66825bb16ceb5b6a01126e1f2391b085dba8da44ee...,0.006169,0.000801,0.011587,0.002164
140484,140484,f772af6720c0b591d49b97946c5e420c1c077affc0f7c7...,0.007472,0.000856,0.004972,0.031333
140485,140485,06b282335bc4853f888e1ab50a6ba23a8e420d42313959...,0.024726,0.001455,0.006492,0.001291
140486,140486,90d423a25d7cdaf674f7d78bc37d88830443ff17717e02...,0.039168,0.001116,0.020141,0.017312
140487,140487,f63e55b226d3732b8b4927be8a2cdc7fb88ff2bb0561e2...,0.005211,0.001137,0.003752,0.004526

In [685]:
df.drop(columns = ['Unnamed: 0'])

,client_id,target_1,target_2,target_3,target_4
0,2b7ff0c1c99cefe259ed83c5dfa0a403f2cbc88032b671...,0.001422,0.000176,0.088572,0.003422
1,0433d23e224b7a520656da6181efadb8d556bb293158c9...,0.014299,0.000435,0.010419,0.003007
2,f2ce8b292e5f9f778f3e20db7608ac76dc8812113a2631...,0.017853,0.007523,0.010701,0.021349
3,4f807e8b163c653bcaeff9f925983568f4c3e6b1a1f231...,0.010975,0.004356,0.025208,0.026687
4,64369f6f8ae1b719332ee1bfb2b454e642b2053d2c9b8a...,0.010453,0.000531,0.010711,0.001758
...,...,...,...,...,...
140483,d49a66825bb16ceb5b6a01126e1f2391b085dba8da44ee...,0.010042,0.002497,0.017207,0.007788
140484,f772af6720c0b591d49b97946c5e420c1c077affc0f7c7...,0.008701,0.000476,0.004393,0.016346
140485,06b282335bc4853f888e1ab50a6ba23a8e420d42313959...,0.009764,0.002151,0.010213,0.002264
140486,90d423a25d7cdaf674f7d78bc37d88830443ff17717e02...,0.016902,0.000972,0.014184,0.037340
140487,f63e55b226d3732b8b4927be8a2cdc7fb88ff2bb0561e2...,0.007528,0.000687,0.004786,0.004292

In [ ]:
l['target_1']

In [679]:
df.to_csv('test.csv',index=False)

In [697]:
df = pd.read_csv("test.csv",index_col=None)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140488 entries, 0 to 140487
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  140488 non-null  int64
 1   client_id   140488 non-null  object
 2   target_1    140488 non-null  float64
 3   target_2    140488 non-null  float64
 4   target_3    140488 non-null  float64
 5   target_4    140488 non-null  float64
dtypes: float64(4), int64(1), object(1)
memory usage: 6.4+ MB

In [693]:
df = pd.read_csv("sample_submission.csv",index_col=None)
df

,Unnamed: 0,client_id,target_1,target_2,target_3,target_4
0,0,2b7ff0c1c99cefe259ed83c5dfa0a403f2cbc88032b671...,0.001422,0.000176,0.088572,0.003422
1,1,0433d23e224b7a520656da6181efadb8d556bb293158c9...,0.014299,0.000435,0.010419,0.003007
2,2,f2ce8b292e5f9f778f3e20db7608ac76dc8812113a2631...,0.017853,0.007523,0.010701,0.021349
3,3,4f807e8b163c653bcaeff9f925983568f4c3e6b1a1f231...,0.010975,0.004356,0.025208,0.026687
4,4,64369f6f8ae1b719332ee1bfb2b454e642b2053d2c9b8a...,0.010453,0.000531,0.010711,0.001758
...,...,...,...,...,...,...
140483,140483,d49a66825bb16ceb5b6a01126e1f2391b085dba8da44ee...,0.010042,0.002497,0.017207,0.007788
140484,140484,f772af6720c0b591d49b97946c5e420c1c077affc0f7c7...,0.008701,0.000476,0.004393,0.016346
140485,140485,06b282335bc4853f888e1ab50a6ba23a8e420d42313959...,0.009764,0.002151,0.010213,0.002264
140486,140486,90d423a25d7cdaf674f7d78bc37d88830443ff17717e02...,0.016902,0.000972,0.014184,0.037340
140487,140487,f63e55b226d3732b8b4927be8a2cdc7fb88ff2bb0561e2...,0.007528,0.000687,0.004786,0.004292

In [667]:
from sklearn.metrics import log_loss

In [ ]:
def objective(trial):
    params = {
        'iterations': trial.suggest_int('iterations', 50, 500),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'depth': trial.suggest_int('depth', 4, 10),
        'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 1e-8, 10.0),
        'border_count': trial.suggest_int('border_count', 1, 255),
    }

    model = MultiOutputClassifier(CatBoostClassifier(**params, verbose=0))
    model.fit(X_train, y_train)

    y_pred_proba = model.predict_proba(X_test)
    log_losses = [log_loss(y_test.iloc[:, i], y_pred_proba[i]) for i in range(y_test.shape[1])]
    return sum(log_losses) / len(log_losses)

# Оптимизация гиперпараметров
study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=50)

# Лучшие параметры
best_params = study.best_params
print("Best parameters:", best_params)

# Обучение модели с лучшими параметрами на всех данных
best_model = MultiOutputClassifier(CatBoostClassifier(**best_params, verbose=0))
best_model.fit(features, targets)

[I 2024-06-16 22:02:27,132] A new study created in memory with name: no-name-8898c6e2-a509-46a2-b0f4-929425e3a85f
[I 2024-06-16 22:02:51,824] Trial 0 finished with value: 0.03131037862417109 and parameters: {'iterations': 350, 'learning_rate': 0.04358636161077776, 'depth': 4, 'l2_leaf_reg': 9.781414759768492, 'border_count': 182}. Best is trial 0 with value: 0.03131037862417109.
[I 2024-06-16 22:03:58,211] Trial 1 finished with value: 0.03127700465290435 and parameters: {'iterations': 179, 'learning_rate': 0.05205416635956212, 'depth': 10, 'l2_leaf_reg': 7.200558788804337, 'border_count': 186}. Best is trial 1 with value: 0.03127700465290435.
[I 2024-06-16 22:04:14,462] Trial 2 finished with value: 0.03216098332590215 and parameters: {'iterations': 151, 'learning_rate': 0.017298355110653835, 'depth': 7, 'l2_leaf_reg': 4.230470627462633, 'border_count': 207}. Best is trial 1 with value: 0.03127700465290435.
[I 2024-06-16 22:04:20,006] Trial 3 finished with value: 0.03133831619492 and parameters: {'iterations': 68, 'learning_rate': 0.24213287131778127, 'depth': 5, 'l2_leaf_reg': 9.630263715925425, 'border_count': 51}. Best is trial 1 with value: 0.03127700465290435.
[I 2024-06-16 22:04:46,244] Trial 4 finished with value: 0.031382842047274574 and parameters: {'iterations': 104, 'learning_rate': 0.05299319872226375, 'depth': 10, 'l2_leaf_reg': 6.796982127934352, 'border_count': 56}. Best is trial 1 with value: 0.03127700465290435.
[I 2024-06-16 22:05:09,673] Trial 5 finished with value: 0.032054511358299106 and parameters: {'iterations': 332, 'learning_rate': 0.23518618694426624, 'depth': 4, 'l2_leaf_reg': 3.681431134969269, 'border_count': 118}. Best is trial 1 with value: 0.03127700465290435.
[I 2024-06-16 22:05:28,804] Trial 6 finished with value: 0.03148686274297404 and parameters: {'iterations': 254, 'learning_rate': 0.17752130244151806, 'depth': 5, 'l2_leaf_reg': 9.051750671023864, 'border_count': 47}. Best is trial 1 with value: 0.03127700465290435.
[I 2024-06-16 22:06:00,638] Trial 7 finished with value: 0.03497772320091774 and parameters: {'iterations': 316, 'learning_rate': 0.17488059192285405, 'depth': 8, 'l2_leaf_reg': 7.4218447821456035, 'border_count': 12}. Best is trial 1 with value: 0.03127700465290435.
[I 2024-06-16 22:06:34,503] Trial 8 finished with value: 0.032932873427363805 and parameters: {'iterations': 447, 'learning_rate': 0.2572309310483844, 'depth': 5, 'l2_leaf_reg': 6.963441272477066, 'border_count': 134}. Best is trial 1 with value: 0.03127700465290435.
[I 2024-06-16 22:06:52,938] Trial 9 finished with value: 0.031616032145426014 and parameters: {'iterations': 153, 'learning_rate': 0.10858517076086911, 'depth': 8, 'l2_leaf_reg': 2.818525381492194, 'border_count': 118}. Best is trial 1 with value: 0.03127700465290435.
[I 2024-06-16 22:08:22,061] Trial 10 finished with value: 0.044525686551812396 and parameters: {'iterations': 219, 'learning_rate': 0.10727400618294985, 'depth': 10, 'l2_leaf_reg': 0.02622755923599751, 'border_count': 239}. Best is trial 1 with value: 0.03127700465290435.
[I 2024-06-16 22:09:05,182] Trial 11 finished with value: 0.03126131618630722 and parameters: {'iterations': 422, 'learning_rate': 0.07245921978795745, 'depth': 7, 'l2_leaf_reg': 8.78207784437794, 'border_count': 183}. Best is trial 11 with value: 0.03126131618630722.
[I 2024-06-16 22:09:55,614] Trial 12 finished with value: 0.03183035655868898 and parameters: {'iterations': 496, 'learning_rate': 0.09110118246465158, 'depth': 7, 'l2_leaf_reg': 6.08395666700846, 'border_count': 175}. Best is trial 11 with value: 0.03126131618630722.
[I 2024-06-16 22:11:10,902] Trial 13 finished with value: 0.031698257460298744 and parameters: {'iterations': 405, 'learning_rate': 0.07500083322152869, 'depth': 9, 'l2_leaf_reg': 8.059261686142149, 'border_count': 247}. Best is trial 11 with value: 0.03126131618630722.
[I 2024-06-16 22:11:31,383] Trial 14 finished with value: 0.03147601714259245 and parameters: {'iterations': 237, 'learning_rate': 0.13771969350996577, 'depth': 6, 'l2_leaf_reg': 5.424195257696177, 'border_count': 157}. Best is trial 11 with value: 0.03126131618630722.
[I 2024-06-16 22:11:54,912] Trial 15 finished with value: 0.03136420158981527 and parameters: {'iterations': 178, 'learning_rate': 0.03238873542653798, 'depth': 8, 'l2_leaf_reg': 8.75203645785966, 'border_count': 211}. Best is trial 11 with value: 0.03126131618630722.
[I 2024-06-16 22:13:03,621] Trial 16 finished with value: 0.03326080291069593 and parameters: {'iterations': 395, 'learning_rate': 0.1470683737262233, 'depth': 9, 'l2_leaf_reg': 8.172657448523784, 'border_count': 214}. Best is trial 11 with value: 0.03126131618630722.
[I 2024-06-16 22:13:28,337] Trial 17 finished with value: 0.031188353559421456 and parameters: {'iterations': 296, 'learning_rate': 0.06743815543907687, 'depth': 6, 'l2_leaf_reg': 5.9513469091151405, 'border_count': 86}. Best is trial 17 with value: 0.031188353559421456.
[I 2024-06-16 22:13:53,178] Trial 18 finished with value: 0.03367011131421944 and parameters: {'iterations': 298, 'learning_rate': 0.20535840790951476, 'depth': 6, 'l2_leaf_reg': 1.5519497585270736, 'border_count': 91}. Best is trial 17 with value: 0.031188353559421456.
[I 2024-06-16 22:14:25,386] Trial 19 finished with value: 0.03470517065721256 and parameters: {'iterations': 388, 'learning_rate': 0.29263316490502367, 'depth': 6, 'l2_leaf_reg': 5.095191787137414, 'border_count': 90}. Best is trial 17 with value: 0.031188353559421456.
[I 2024-06-16 22:15:13,096] Trial 20 finished with value: 0.03229660923269035 and parameters: {'iterations': 499, 'learning_rate': 0.12222348931588341, 'depth': 7, 'l2_leaf_reg': 6.001283884911969, 'border_count': 148}. Best is trial 17 with value: 0.031188353559421456.
[I 2024-06-16 22:15:40,655] Trial 21 finished with value: 0.031242093815129175 and parameters: {'iterations': 276, 'learning_rate': 0.06718202178939447, 'depth': 7, 'l2_leaf_reg': 7.590383702920468, 'border_count': 185}. Best is trial 17 with value: 0.031188353559421456.
[I 2024-06-16 22:16:07,848] Trial 22 finished with value: 0.031188695793649763 and parameters: {'iterations': 291, 'learning_rate': 0.07619107160034962, 'depth': 7, 'l2_leaf_reg': 8.174903540341486, 'border_count': 83}. Best is trial 17 with value: 0.031188353559421456.
[I 2024-06-16 22:16:31,214] Trial 23 finished with value: 0.031158899324222618 and parameters: {'iterations': 281, 'learning_rate': 0.07864574741952098, 'depth': 6, 'l2_leaf_reg': 6.314278361097999, 'border_count': 87}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:17:02,662] Trial 24 finished with value: 0.031530111073562885 and parameters: {'iterations': 361, 'learning_rate': 0.012904967156304403, 'depth': 6, 'l2_leaf_reg': 6.244290292452105, 'border_count': 86}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:17:24,779] Trial 25 finished with value: 0.031259157725076425 and parameters: {'iterations': 284, 'learning_rate': 0.09462772220076165, 'depth': 5, 'l2_leaf_reg': 4.0524487979132715, 'border_count': 69}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:17:42,584] Trial 26 finished with value: 0.03131860498772753 and parameters: {'iterations': 212, 'learning_rate': 0.082887237844406, 'depth': 6, 'l2_leaf_reg': 4.7194801927491925, 'border_count': 23}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:18:12,762] Trial 27 finished with value: 0.03198930216619157 and parameters: {'iterations': 254, 'learning_rate': 0.1260361614136164, 'depth': 8, 'l2_leaf_reg': 5.57287812848544, 'border_count': 106}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:18:39,627] Trial 28 finished with value: 0.03226816999830551 and parameters: {'iterations': 315, 'learning_rate': 0.17225964205555233, 'depth': 6, 'l2_leaf_reg': 6.440895350888118, 'border_count': 36}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:19:03,800] Trial 29 finished with value: 0.03131840736819126 and parameters: {'iterations': 357, 'learning_rate': 0.03374636523416201, 'depth': 4, 'l2_leaf_reg': 9.961587341024366, 'border_count': 83}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:19:31,715] Trial 30 finished with value: 0.031210299217611585 and parameters: {'iterations': 364, 'learning_rate': 0.056844808750287995, 'depth': 5, 'l2_leaf_reg': 3.3818248590998303, 'border_count': 69}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:20:00,058] Trial 31 finished with value: 0.031232075810914493 and parameters: {'iterations': 355, 'learning_rate': 0.032693502684441614, 'depth': 5, 'l2_leaf_reg': 2.968002307864351, 'border_count': 70}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:20:21,057] Trial 32 finished with value: 0.03129974472988435 and parameters: {'iterations': 302, 'learning_rate': 0.05467753838685417, 'depth': 4, 'l2_leaf_reg': 1.9758413191312112, 'border_count': 106}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:20:49,614] Trial 33 finished with value: 0.031202194927072026 and parameters: {'iterations': 334, 'learning_rate': 0.054614386181196586, 'depth': 6, 'l2_leaf_reg': 4.644145027949946, 'border_count': 69}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:21:13,665] Trial 34 finished with value: 0.0315982403658562 and parameters: {'iterations': 259, 'learning_rate': 0.10072405830159004, 'depth': 7, 'l2_leaf_reg': 4.617375746571531, 'border_count': 35}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:21:42,503] Trial 35 finished with value: 0.031192996193059448 and parameters: {'iterations': 336, 'learning_rate': 0.03965749561873415, 'depth': 6, 'l2_leaf_reg': 5.458173244652684, 'border_count': 104}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:22:04,024] Trial 36 finished with value: 0.03248906263298844 and parameters: {'iterations': 209, 'learning_rate': 0.010982574561319403, 'depth': 7, 'l2_leaf_reg': 6.875242173064836, 'border_count': 103}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:22:29,006] Trial 37 finished with value: 0.03121962534177122 and parameters: {'iterations': 281, 'learning_rate': 0.033104948656527806, 'depth': 6, 'l2_leaf_reg': 5.5189025024581175, 'border_count': 135}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:22:57,508] Trial 38 finished with value: 0.031173612108577574 and parameters: {'iterations': 335, 'learning_rate': 0.0408279878275091, 'depth': 6, 'l2_leaf_reg': 7.676550318103171, 'border_count': 123}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:23:15,700] Trial 39 finished with value: 0.031239997085934113 and parameters: {'iterations': 235, 'learning_rate': 0.06562341896730975, 'depth': 5, 'l2_leaf_reg': 7.928396388781225, 'border_count': 121}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:23:33,344] Trial 40 finished with value: 0.03154319529388289 and parameters: {'iterations': 109, 'learning_rate': 0.12341900646208834, 'depth': 9, 'l2_leaf_reg': 9.5351279587236, 'border_count': 138}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:24:01,430] Trial 41 finished with value: 0.031201569135658067 and parameters: {'iterations': 329, 'learning_rate': 0.04418897278954248, 'depth': 6, 'l2_leaf_reg': 7.25858022018242, 'border_count': 101}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:24:29,403] Trial 42 finished with value: 0.03131599122581245 and parameters: {'iterations': 338, 'learning_rate': 0.08459947518922109, 'depth': 6, 'l2_leaf_reg': 6.658057338405737, 'border_count': 55}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:24:59,637] Trial 43 finished with value: 0.031197629855145112 and parameters: {'iterations': 308, 'learning_rate': 0.04070926408637965, 'depth': 7, 'l2_leaf_reg': 5.833528519995325, 'border_count': 120}. Best is trial 23 with value: 0.031158899324222618.
[I 2024-06-16 22:25:28,829] Trial 44 finished with value: 0.03131062382627455 and parameters: {'iterations': 378, 'learning_rate': 0.02343584868478191, 'depth': 5, 'l2_leaf_reg': 8.402836729213211, 'border_count': 163}. Best is trial 23 with value: 0.031158899324222618.